const nigeria = [
    'Lagos',
    'Ikeja , Lagos',
    'Maryland , Ikeja , Lagos',
    'Ikeja GRA , Ikeja , Lagos',
    'Alausa , Ikeja , Lagos',
    'Oregun , Ikeja , Lagos',
    'Obafemi Awolowo Way , Ikeja , Lagos',
    'Allen Avenue , Ikeja , Lagos',
    'Opebi , Ikeja , Lagos',
    'Adeniyi Jones , Ikeja , Lagos',
    'Agidingbi , Ikeja , Lagos',
    'Mobolaji Bank Anthony Way , Ikeja , Lagos',
    'Toyin street , Ikeja , Lagos',
    'Oba Akran , Ikeja , Lagos',
    'Balogun , Ikeja , Lagos',
    'Awolowo way , Ikeja , Lagos',
    'Unity Road , Ikeja , Lagos',
    'Airport Road(Ikeja) , Ikeja , Lagos',
    'Mangoro , Ikeja , Lagos',
    'Surulere , Lagos',
    'Aguda , Surulere , Lagos',
    'Coker , Surulere , Lagos',
    'Adelabu , Surulere , Lagos',
    'Eric moore , Surulere , Lagos',
    'Alaka Estate , Surulere , Lagos',
    'Gbaja , Surulere , Lagos',
    'Itire , Surulere , Lagos',
    'Lawanson , Surulere , Lagos',
    'Ijesha , Surulere , Lagos',
    'Bode Thomas , Surulere , Lagos',
    'Adeniran Ogunsanya , Surulere , Lagos',
    'Ogunlana , Surulere , Lagos',
    'Alaka/Iponri , Surulere , Lagos',
    'Kilo-Marsha , Surulere , Lagos',
    'Orile-Iganmu , Surulere , Lagos',
    'Masha , Surulere , Lagos',
    'idi- Araba , Surulere , Lagos',
    'Iponri , Surulere , Lagos',
    'Ojuelegba , Surulere , Lagos',
    'Abraham Adesanya , Surulere , Lagos',
    'Western Avenue , Surulere , Lagos',
    'Randle Avenue , Surulere , Lagos',
    'Ojota , Lagos',
    'Ojota , Ojota , Lagos',
    'Ogudu Road , Ojota , Lagos',
    'Shomolu , Lagos',
    'Shomolu , Shomolu , Lagos',
    'Ikorodu Road , Shomolu , Lagos',
    'Obanikoro , Shomolu , Lagos',
    'Bariga , Shomolu , Lagos',
    'Onipanu , Shomolu , Lagos',
    'Palmgroove , Shomolu , Lagos',
    'Fadeyi , Shomolu , Lagos',
    'Ojodu , Lagos',
    'Omole phase 1 , Ojodu , Lagos',
    'Magodo GRA Phase 1 , Ojodu , Lagos',
    'Omole phase 2 , Ojodu , Lagos',
    'Olowora , Ojodu , Lagos',
    'Berger , Ojodu , Lagos',
    'Yakoyo/Alagbole , Ojodu , Lagos',
    'River valley estate , Ojodu , Lagos',
    'Unity estate , Ojodu , Lagos',
    'Morgan estate , Ojodu , Lagos',
    'Williams estate , Ojodu , Lagos',
    'Isheri North , Ojodu , Lagos',
    'Oshodi , Lagos',
    'Oshodi Expressway , Oshodi , Lagos',
    'Arowojobe , Oshodi , Lagos',
    'Shogunle , Oshodi , Lagos',
    'Mafoluku , Oshodi , Lagos',
    'Airport Road , Oshodi , Lagos',
    'Ojuwoye , Oshodi , Lagos',
    'Bolade , Oshodi , Lagos',
    'Kosofe/Ikosi , Lagos',
    'Ketu , Kosofe/Ikosi , Lagos',
    'Magodo , Kosofe/Ikosi , Lagos',
    'Shangisha , Kosofe/Ikosi , Lagos',
    'Alapere , Kosofe/Ikosi , Lagos',
    'Kosofe , Kosofe/Ikosi , Lagos',
    'Magodo GRA Phase 2 , Kosofe/Ikosi , Lagos',
    'Ikosi-Ketu , Kosofe/Ikosi , Lagos',
    'Mile 12 , Kosofe/Ikosi , Lagos',
    'CMD Road , Kosofe/Ikosi , Lagos',
    'Yaba , Lagos',
    'Ebute Metta , Yaba , Lagos',
    'Onike , Yaba , Lagos',
    'Iwaya , Yaba , Lagos',
    'Fola Agoro , Yaba , Lagos',
    'Tejuosho , Yaba , Lagos',
    'Jibowu , Yaba , Lagos',
    'Sabo , Yaba , Lagos',
    'Alagomeji , Yaba , Lagos',
    'Adekunle , Yaba , Lagos',
    'Akoka , Yaba , Lagos',
    'Abule-Oja , Yaba , Lagos',
    'Abule-Ijesha , Yaba , Lagos',
    'Ikoyi , Lagos',
    'Mojisola Onikoyi Estate , Ikoyi , Lagos',
    'Banana Island , Ikoyi , Lagos',
    'Parkview Estate , Ikoyi , Lagos',
    'Bourdillon , Ikoyi , Lagos',
    'Dolphin Estate , Ikoyi , Lagos',
    'Falomo , Ikoyi , Lagos',
    'Old Ikoyi , Ikoyi , Lagos',
    'Abacha Estate , Ikoyi , Lagos',
    'Osborne Foreshore Estate , Ikoyi , Lagos',
    'Ikoyi S.W , Ikoyi , Lagos',
    '2nd Avenue Extension , Ikoyi , Lagos',
    'Awolowo Road , Ikoyi , Lagos',
    'Gerard road , Ikoyi , Lagos',
    'Mosley Road , Ikoyi , Lagos',
    'MacPherson , Ikoyi , Lagos',
    'Lagos Island , Lagos',
    'Lagos Island , Lagos Island , Lagos',
    'Apongbon , Lagos Island , Lagos',
    'C.M.S , Lagos Island , Lagos',
    'Marina , Lagos Island , Lagos',
    'Obalende , Lagos Island , Lagos',
    'Onikan , Lagos Island , Lagos',
    'Victoria Island , Lagos',
    'ONIRU , Victoria Island , Lagos',
    '1004 , Victoria Island , Lagos',
    'Victoria Island Extension , Victoria Island , Lagos',
    'Adeola Odeku , Victoria Island , Lagos',
    'Kofo Abayomi , Victoria Island , Lagos',
    'Karimu Kotun , Victoria Island , Lagos',
    'Tiamiyu Savage , Victoria Island , Lagos',
    'Sanusi Fafunwa , Victoria Island , Lagos',
    'Akin Olugbade , Victoria Island , Lagos',
    'Ahmadu Bello Way , Victoria Island , Lagos',
    'Bonny Camp , Victoria Island , Lagos',
    'Saka Tinubu , Victoria Island , Lagos',
    'Idowu Taylor , Victoria Island , Lagos',
    'Adeola Hopewell , Victoria Island , Lagos',
    'Ademola Adetokunbo , Victoria Island , Lagos',
    'Akin Adesola , Victoria Island , Lagos',
    'Ligali Ayorinde , Victoria Island , Lagos',
    'Eko Atlantic , Victoria Island , Lagos',
    'Lekki , Lagos',
    'Ikate , Lekki , Lagos',
    'Lekki Phase 2 , Lekki , Lagos',
    'Agungi , Lekki , Lagos',
    'Igbo-efon , Lekki , Lagos',
    'Osapa london , Lekki , Lagos',
    'chevron , Lekki , Lagos',
    'Ilasan , Lekki , Lagos',
    'Lekki Phase 1 , Lekki , Lagos',
    'Jakande , Lekki , Lagos',
    'Ikota , Lekki , Lagos',
    'VGC , Lekki , Lagos',
    'Idado , Lekki , Lagos',
    'Nicon Town , Lekki , Lagos',
    'Ologolo , Lekki , Lagos',
    'Oral Estate , Lekki , Lagos',
    'Along Lekki Expressway , Lekki , Lagos',
    'orchid , Lekki , Lagos',
    'Ajah , Lagos',
    'Ilaje , Ajah , Lagos',
    'Sangotedo , Ajah , Lagos',
    'Abijo , Ajah , Lagos',
    'Awoyaya , Ajah , Lagos',
    'Lakowe , Ajah , Lagos',
    'Badore , Ajah , Lagos',
    'Abraham adesanya estate , Ajah , Lagos',
    'Canaan Estate , Ajah , Lagos',
    'Ado , Ajah , Lagos',
    'Crown Estate , Ajah , Lagos',
    'Eden garden Estate , Ajah , Lagos',
    'Graceland Estate , Ajah , Lagos',
    'Lekki Gardens estate , Ajah , Lagos',
    'Ogombo , Ajah , Lagos',
    'Peninsula Estate , Ajah , Lagos',
    'Thomas estate , Ajah , Lagos',
    'Off Lekki-Epe Expressway , Ajah , Lagos',
    'Ajiwe , Ajah , Lagos',
    'Olokonla , Ajah , Lagos',
    'Ajiran , Ajah , Lagos',
    'Akodo , Ajah , Lagos',
    'Okun Ajah , Ajah , Lagos',
    'Lekki Scheme 2 , Ajah , Lagos',
    'Apapa , Lagos',
    'Apapa G.R.A , Apapa , Lagos',
    'Kirikiri 1 , Apapa , Lagos',
    'Liverpool , Apapa , Lagos',
    'Olodi Apapa , Apapa , Lagos',
    'Trade fair , Apapa , Lagos',
    'Ajegunle , Apapa , Lagos',
    'Tin Can , Apapa , Lagos',
    'Kirikiri , Apapa , Lagos',
    'Apapa road , Apapa , Lagos',
    'Ijora , Apapa , Lagos',
    'Snake island , Apapa , Lagos',
    'Agege , Lagos',
    'Ifako , Agege , Lagos',
    'Iju , Agege , Lagos',
    'orile agege , Agege , Lagos',
    'Agbotikuyo , Agege , Lagos',
    'Pen cinema , Agege , Lagos',
    'Oko oba , Agege , Lagos',
    'Capitol , Agege , Lagos',
    'Oko oba road , Agege , Lagos',
    'LSDPC estate , Agege , Lagos',
    'Fagba , Agege , Lagos',
    'Cement , Agege , Lagos',
    'Dopemu , Agege , Lagos',
    'Onitiri , Agege , Lagos',
    'Iju-Ishaga , Agege , Lagos',
    'Mulero , Agege , Lagos',
    'Oke-Odo , Agege , Lagos',
    'Idi Oro , Agege , Lagos',
    'Isolo , Lagos',
    'Ajao Estate , Isolo , Lagos',
    'Ire Akari , Isolo , Lagos',
    'Bucknor , Isolo , Lagos',
    'Kogberegbe street , Isolo , Lagos',
    'Oke-Afa , Isolo , Lagos',
    'Osolo way , Isolo , Lagos',
    'Jakande Estate , Isolo , Lagos',
    'Amuwo Odofin , Lagos',
    'Festac , Amuwo Odofin , Lagos',
    'Amuwo Odofin , Amuwo Odofin , Lagos',
    'Satellite Town , Amuwo Odofin , Lagos',
    'Agboju , Amuwo Odofin , Lagos',
    'Green estate , Amuwo Odofin , Lagos',
    'Apple junction , Amuwo Odofin , Lagos',
    'Alakija , Amuwo Odofin , Lagos',
    'Ikorodu , Lagos',
    'Ikorodu , Ikorodu , Lagos',
    'Ebute , Ikorodu , Lagos',
    'Ijede , Ikorodu , Lagos',
    'Odongunyan , Ikorodu , Lagos',
    'Igbogbo , Ikorodu , Lagos',
    'Agric , Ikorodu , Lagos',
    'Akute Ajuwon , Ikorodu , Lagos',
    'Jumofak , Ikorodu , Lagos',
    'Ibeshe , Ikorodu , Lagos',
    'Ipakodo , Ikorodu , Lagos',
    'Isawo , Ikorodu , Lagos',
    'Apeka , Ikorodu , Lagos',
    'Maya , Ikorodu , Lagos',
    'Ibeju-Lekki , Lagos',
    'Eleko , Ibeju-Lekki , Lagos',
    'LBS , Ibeju-Lekki , Lagos',
    'Free Trade Zone , Ibeju-Lekki , Lagos',
    'Eputu , Ibeju-Lekki , Lagos',
    'Akodo Ise , Ibeju-Lekki , Lagos',
    'Ise town , Ibeju-Lekki , Lagos',
    'LaCampaigne Tropicana , Ibeju-Lekki , Lagos',
    'Eleranigbe , Ibeju-Lekki , Lagos',
    'Alatise , Ibeju-Lekki , Lagos',
    'Arapagi Oloko , Ibeju-Lekki , Lagos',
    'Eluju , Ibeju-Lekki , Lagos',
    'Iberekodo , Ibeju-Lekki , Lagos',
    'Ikegun , Ibeju-Lekki , Lagos',
    'Mosere Ikoga , Ibeju-Lekki , Lagos',
    'Ogogoro , Ibeju-Lekki , Lagos',
    'Okunraiye , Ibeju-Lekki , Lagos',
    'Oribanwa , Ibeju-Lekki , Lagos',
    'Orimedu , Ibeju-Lekki , Lagos',
    'Origanrigan , Ibeju-Lekki , Lagos',
    'Ojo , Lagos',
    'Ojo , Ojo , Lagos',
    'Iba , Ojo , Lagos',
    'Okokomaiko , Ojo , Lagos',
    'Ajangbadi , Ojo , Lagos',
    'Alaba , Ojo , Lagos',
    'Iju , Lagos',
    'Ikotun/Igando , Lagos',
    'Ikotun , Ikotun/Igando , Lagos',
    'Igando , Ikotun/Igando , Lagos',
    'Egbe , Ikotun/Igando , Lagos',
    'Ijegun , Ikotun/Igando , Lagos',
    'Abaranje , Ikotun/Igando , Lagos',
    'Governors road , Ikotun/Igando , Lagos',
    'Egan , Ikotun/Igando , Lagos',
    'Egbe/Idimu , Lagos',
    'Isheri , Egbe/Idimu , Lagos',
    'council , Egbe/Idimu , Lagos',
    'Idimu , Egbe/Idimu , Lagos',
    'College , Egbe/Idimu , Lagos',
    'Arida , Egbe/Idimu , Lagos',
    'Pap , Egbe/Idimu , Lagos',
    'Ipaja , Lagos',
    'Iyana Ipaja , Ipaja , Lagos',
    'Gowon Estate , Ipaja , Lagos',
    'Ayobo , Ipaja , Lagos',
    'Ipaja , Ipaja , Lagos',
    'Baruwa , Ipaja , Lagos',
    'Ipaja road , Ipaja , Lagos',
    'Boys Town , Ipaja , Lagos',
    'Isefun , Ipaja , Lagos',
    'Abule Egba , Lagos',
    'Alagbado , Abule Egba , Lagos',
    'Abule Egba , Abule Egba , Lagos',
    'Ojokoro , Abule Egba , Lagos',
    'New oko oba , Abule Egba , Lagos',
    'Ogudu , Lagos',
    'Ogudu , Ogudu , Lagos',
    'Ogudu GRA , Ogudu , Lagos',
    'Ogudu-Orike , Ogudu , Lagos',
    'Mushin , Lagos',
    'Ladipo , Mushin , Lagos',
    'Ilasamaja , Mushin , Lagos',
    'Mushin , Mushin , Lagos',
    'Olateju , Mushin , Lagos',
    'Papa Ajao , Mushin , Lagos',
    'Okota , Lagos',
    'Ago palace , Okota , Lagos',
    'Community road , Okota , Lagos',
    'Owolabi junction , Okota , Lagos',
    'Gbagada , Lagos',
    'Ifako-gbagada , Gbagada , Lagos',
    'Atunrase Medina , Gbagada , Lagos',
    'Millenuim/UPS , Gbagada , Lagos',
    'Oworonshoki , Gbagada , Lagos',
    'Soluyi , Gbagada , Lagos',
    'Phase 1 , Gbagada , Lagos',
    'Phase 2 , Gbagada , Lagos',
    'Medina , Gbagada , Lagos',
    'New garage , Gbagada , Lagos',
    'Maryland , Lagos',
    'Anthony Village , Maryland , Lagos',
    'LSDPC Maryland Estate , Maryland , Lagos',
    'Mende , Maryland , Lagos',
    'Shonibare Estate , Maryland , Lagos',
    'Sangotedo , Lagos',
    'Majek , Sangotedo , Lagos',
    'Bogije , Sangotedo , Lagos',
    'Monastery road , Sangotedo , Lagos',
    'Alimosho , Lagos',
    'Egbeda , Alimosho , Lagos',
    'Akowonjo , Alimosho , Lagos',
    'Pipeline , Alimosho , Lagos',
    'Shasha , Alimosho , Lagos',
    'Orisunbare , Alimosho , Lagos',
    'Akesan , Alimosho , Lagos',
    'Ilupeju , Lagos',
    'Town planning way , Ilupeju , Lagos',
    'Bye pass Ilupeju , Ilupeju , Lagos',
    'Ilupeju industrial estate , Ilupeju , Lagos',
    'Coker Road , Ilupeju , Lagos',
    'Ikorodu road(Ilupeju) , Ilupeju , Lagos',
    'Orile , Lagos',
    'Iganmu , Orile , Lagos',
    'Mile 2 , Orile , Lagos',
    'Badagry , Lagos',
    'Magbon , Badagry , Lagos',
    'Badagry , Badagry , Lagos',
    'Age Mowo , Badagry , Lagos',
    'Ajido , Badagry , Lagos',
    'Aradagun , Badagry , Lagos',
    'Oko Afo , Badagry , Lagos',
    'Ejigbo , Lagos',
    'Ife-Odan , Ejigbo , Lagos',
    'Ilawo , Ejigbo , Lagos',
    'Olla , Ejigbo , Lagos',
    'Ejigbo , Ejigbo , Lagos',
    'Orilowo , Ejigbo , Lagos',
    'Ketu , Lagos',
    'Ogba , Lagos',
    'OGBA GRA , Ogba , Lagos',
    'Acme road , Ogba , Lagos',
    'Oke-Ira , Ogba , Lagos',
    'Aguda(Ogba) , Ogba , Lagos',
    'Ogba Industrial , Ogba , Lagos',
    'Ifako-ogba , Ogba , Lagos',
    'Wempco road , Ogba , Lagos',
    'Ajayi road , Ogba , Lagos',
    'Ogba Bus-stop , Ogba , Lagos',
    'Epe , Lagos',
    'Epe Road , Epe , Lagos',
    'Bariga , Lagos',
    'Abuja',
    'Phase 1 , Abuja',
    'Central Area , Phase 1 , Abuja',
    'Garki 1 , Phase 1 , Abuja',
    'Garki 2 , Phase 1 , Abuja',
    'Wuse 1 , Phase 1 , Abuja',
    'Wuse 2 , Phase 1 , Abuja',
    'Asokoro , Phase 1 , Abuja',
    'Maitama , Phase 1 , Abuja',
    'Guzape , Phase 1 , Abuja',
    'Mabushi , Phase 1 , Abuja',
    'Phase 2 , Abuja',
    'Kukwuaba , Phase 2 , Abuja',
    'Gudu , Phase 2 , Abuja',
    'Durumi , Phase 2 , Abuja',
    'Wuye , Phase 2 , Abuja',
    'Jabi , Phase 2 , Abuja',
    'Utako , Phase 2 , Abuja',
    'Jahi , Phase 2 , Abuja',
    'Kado , Phase 2 , Abuja',
    'Dakibiyu , Phase 2 , Abuja',
    'Kaura (Games Village) , Phase 2 , Abuja',
    'Duboyi , Phase 2 , Abuja',
    'Gaduwa , Phase 2 , Abuja',
    'Dutse , Phase 2 , Abuja',
    'Katampe Ext , Phase 2 , Abuja',
    'Katampe Main , Phase 2 , Abuja',
    'Apo , Phase 2 , Abuja',
    'Lokogoma , Phase 2 , Abuja',
    'Phase 3 , Abuja',
    'Karmo , Phase 3 , Abuja',
    'Gwarinpa , Phase 3 , Abuja',
    'Dape , Phase 3 , Abuja',
    'Kafe , Phase 3 , Abuja',
    'Nbora , Phase 3 , Abuja',
    'Galadinmawa , Phase 3 , Abuja',
    'Dakwo , Phase 3 , Abuja',
    'Wumba , Phase 3 , Abuja',
    'Idu Industrial(Institution and Research) , Phase 3 , Abuja',
    'Kabusa , Phase 3 , Abuja',
    'Karsana , Phase 3 , Abuja',
    'Life Camp , Phase 3 , Abuja',
    'Sub-Urban District , Abuja',
    'Nyanya , Sub-Urban District , Abuja',
    'Karu , Sub-Urban District , Abuja',
    'Gwagwalada , Sub-Urban District , Abuja',
    'Kubwa , Sub-Urban District , Abuja',
    'Jukwoyi , Sub-Urban District , Abuja',
    'Lugbe , Sub-Urban District , Abuja',
    'Chika , Sub-Urban District , Abuja',
    'Kuchigworro , Sub-Urban District , Abuja',
    'Pyakassa , Sub-Urban District , Abuja',
    'Idu , Sub-Urban District , Abuja',
    'Mpape , Sub-Urban District , Abuja',
    'Karimu , Sub-Urban District , Abuja',
    'Gwagwa , Sub-Urban District , Abuja',
    'Dei-Dei , Sub-Urban District , Abuja',
    'Kuje , Sub-Urban District , Abuja',
    'Mararaba , Sub-Urban District , Abuja',
    'Kurudu , Sub-Urban District , Abuja',
    'Apo , Abuja',
    'Asokoro , Abuja',
    'Central Area , Abuja',
    'Dakibiyu , Abuja',
    'Dakwo , Abuja',
    'Dape , Abuja',
    'Duboyi , Abuja',
    'Durumi , Abuja',
    'Gaduwa , Abuja',
    'Galadinmawa , Abuja',
    'Garki 1 , Abuja',
    'Garki 2 , Abuja',
    'Guzape , Abuja',
    'Gwarinpa , Abuja',
    'Idu Industrial(Institution and Research) , Abuja',
    'Jabi , Abuja',
    'Jahi , Abuja',
    'Kabusa , Abuja',
    'Kado , Abuja',
    'Kafe , Abuja',
    'Karmo , Abuja',
    'Karsana , Abuja',
    'Katampe Ext , Abuja',
    'Katampe Main , Abuja',
    'Kaura (Games Village) , Abuja',
    'Kukwuaba , Abuja',
    'Life Camp , Abuja',
    'Lokogoma , Abuja',
    'Mabushi , Abuja',
    'Maitama , Abuja',
    'Nbora , Abuja',
    'Utako , Abuja',
    'Wumba , Abuja',
    'Wuse 1 , Abuja',
    'Wuse 2 , Abuja',
    'Wuye , Abuja',
    'Chika , Abuja',
    'Dei-Dei , Abuja',
    'Gwagwa , Abuja',
    'Gwagwalada , Abuja',
    'Idu , Abuja',
    'Jukwoyi , Abuja',
    'Karimu , Abuja',
    'Kubwa , Abuja',
    'Kuchigworro , Abuja',
    'Kuje , Abuja',
    'Kurudu , Abuja',
    'Lugbe , Abuja',
    'Mararaba , Abuja',
    'Mpape , Abuja',
    'Nyanya , Abuja',
    'Pyakassa , Abuja',
    'Orozo , Abuja',
    'Orozo , Orozo , Abuja',
    'Bwari , Abuja',
    'Rivers',
    'Port Harcourt , Rivers',
    'Trans Amadi , Port Harcourt , Rivers',
    'Bori Kiri , Port Harcourt , Rivers',
    'D-Line , Port Harcourt , Rivers',
    'Diobu mile 1 , Port Harcourt , Rivers',
    'Diobu mile 2 , Port Harcourt , Rivers',
    'Diobu mile 3 , Port Harcourt , Rivers',
    'Diobu mile 4 , Port Harcourt , Rivers',
    'Eagle Island rumueme/Oroakwo , Port Harcourt , Rivers',
    'Ikwerre , Port Harcourt , Rivers',
    'Magbuoba , Port Harcourt , Rivers',
    'New GRA , Port Harcourt , Rivers',
    'New Layout , Port Harcourt , Rivers',
    'Old GRA , Port Harcourt , Rivers',
    'Old Township , Port Harcourt , Rivers',
    'Rumukrueshi , Port Harcourt , Rivers',
    'Rumuokwuta , Port Harcourt , Rivers',
    'Obia-Akpor , Port Harcourt , Rivers',
    'Elizu , Port Harcourt , Rivers',
    'Atali , Port Harcourt , Rivers',
    'Eneka , Port Harcourt , Rivers',
    'Rumuosita , Port Harcourt , Rivers',
    'Igwurta-Ali , Port Harcourt , Rivers',
    'Choba , Port Harcourt , Rivers',
    'Rumuokwurushi , Port Harcourt , Rivers',
    'Rukphakurusi , Port Harcourt , Rivers',
    'Ada George , Port Harcourt , Rivers',
    'Wimpy , Port Harcourt , Rivers',
    'Borikiri , Port Harcourt , Rivers',
    'Eleme , Port Harcourt , Rivers',
    'Eliozu , Port Harcourt , Rivers',
    'Rupkpokwu , Port Harcourt , Rivers',
    'Shell Location , Port Harcourt , Rivers',
    'Port-harcourt/Aba Expressway , Port Harcourt , Rivers',
    'East West Road , Port Harcourt , Rivers',
    'Oyigbo , Port Harcourt , Rivers',
    'Eriebe , Port Harcourt , Rivers',
    'Rumolumeni , Port Harcourt , Rivers',
    'Obio-Akpor , Rivers',
    'Okirika , Rivers',
    'Ogu-obolo , Rivers',
    'Eleme , Rivers',
    'Tai , Rivers',
    'Gokana , Rivers',
    'Khana , Rivers',
    'Oyigbo , Rivers',
    'Opobo-Nkoro , Rivers',
    'Andoni , Rivers',
    'Bonny , Rivers',
    'Degema , Rivers',
    'Asari-Toru , Rivers',
    'Akuku-Toru , Rivers',
    'Abua-Odual , Rivers',
    'Ahoada West , Rivers',
    'Ogba-Egbema-Ndoni , Rivers',
    'Ogba , Ogba-Egbema-Ndoni , Rivers',
    'Ndoni , Ogba-Egbema-Ndoni , Rivers',
    'Egbema , Ogba-Egbema-Ndoni , Rivers',
    'Emohua , Rivers',
    'Ikwerre , Rivers',
    'Etche , Rivers',
    'Omuma , Rivers',
    'Ogun',
    'Agbara-Igbesa , Ogun',
    'Agbara , Agbara-Igbesa , Ogun',
    'Arepo , Ogun',
    'Arepo , Arepo , Ogun',
    'Abeokuta , Ogun',
    'Alabata , Abeokuta , Ogun',
    'Fatola , Abeokuta , Ogun',
    'Kuto , Abeokuta , Ogun',
    'Apakila , Abeokuta , Ogun',
    'Oke Saje , Abeokuta , Ogun',
    'Ago Oko , Abeokuta , Ogun',
    'Ago Ika , Abeokuta , Ogun',
    'Ita Ika , Abeokuta , Ogun',
    'Iyana Mortuary , Abeokuta , Ogun',
    'Idi Aba , Abeokuta , Ogun',
    'Itoku , Abeokuta , Ogun',
    'Adigbe , Abeokuta , Ogun',
    'Somorin , Abeokuta , Ogun',
    'Totoro , Abeokuta , Ogun',
    'Itoko , Abeokuta , Ogun',
    'Eleweran , Abeokuta , Ogun',
    'Asero , Abeokuta , Ogun',
    'Kotopo , Abeokuta , Ogun',
    'Oke Mosan , Abeokuta , Ogun',
    'Ita Eko , Abeokuta , Ogun',
    'Ojeere , Abeokuta , Ogun',
    'Adatan , Abeokuta , Ogun',
    'Isale Ake , Abeokuta , Ogun',
    'Ilugun , Abeokuta , Ogun',
    'Omida , Abeokuta , Ogun',
    'Ikerekodo , Abeokuta , Ogun',
    'Mawuko , Abeokuta , Ogun',
    'Oke Ijeun , Abeokuta , Ogun',
    'Isale Ijeun , Abeokuta , Ogun',
    'Ijeun Titun , Abeokuta , Ogun',
    'Ado Odo/Ota , Ogun',
    'Abebi/Okesuna , Ado Odo/Ota , Ogun',
    'Adalemo , Ado Odo/Ota , Ogun',
    'Sango Ota , Ado Odo/Ota , Ogun',
    'Afowobaje Estate/Agbala Obanibasiri , Ado Odo/Ota , Ogun',
    'Akilo Quarters , Ado Odo/Ota , Ogun',
    'Erinko , Ado Odo/Ota , Ogun',
    'Ota GRA , Ado Odo/Ota , Ogun',
    'Idiroko , Ado Odo/Ota , Ogun',
    'Ijamido , Ado Odo/Ota , Ogun',
    'Ijana Qtrs/ Oke Oyinbo/ Mefun , Ado Odo/Ota , Ogun',
    'Iloje , Ado Odo/Ota , Ogun',
    'Jibowu (Ota) , Ado Odo/Ota , Ogun',
    'Joju , Ado Odo/Ota , Ogun',
    'Ketere , Ado Odo/Ota , Ogun',
    'New Iyanru , Ado Odo/Ota , Ogun',
    'Obasanjo Farm , Ado Odo/Ota , Ogun',
    'Ojabi Quarters , Ado Odo/Ota , Ogun',
    'Oruba Qtrs , Ado Odo/Ota , Ogun',
    'Ota-Idiroko road/Tomori , Ado Odo/Ota , Ogun',
    'Pilo , Ado Odo/Ota , Ogun',
    'Ewekoro , Ogun',
    'Abule Ado , Ewekoro , Ogun',
    'Abese , Ewekoro , Ogun',
    'Papalanto , Ewekoro , Ogun',
    'Ifo , Ogun',
    'Agbado , Ifo , Ogun',
    'Ifo , Ifo , Ogun',
    'Ojoolu , Ifo , Ogun',
    'Ijebu , Ogun',
    'Ijebu East , Ijebu , Ogun',
    'Ijebu North , Ijebu , Ogun',
    'Ijebu North East , Ijebu , Ogun',
    'Ijebu Ode , Ijebu , Ogun',
    'Obafemi Owode , Ogun',
    'Ajebo , Obafemi Owode , Ogun',
    'Ajuru , Obafemi Owode , Ogun',
    'Kajola , Obafemi Owode , Ogun',
    'Alapakooni , Obafemi Owode , Ogun',
    'Mokoloki , Obafemi Owode , Ogun',
    'Mokoloki Asipa , Obafemi Owode , Ogun',
    'Oba , Obafemi Owode , Ogun',
    'Ofada , Obafemi Owode , Ogun',
    'Onidundu , Obafemi Owode , Ogun',
    'Ogun makin , Obafemi Owode , Ogun',
    'Mowe , Obafemi Owode , Ogun',
    'Ibafo , Obafemi Owode , Ogun',
    'Magboro , Obafemi Owode , Ogun',
    'Odogbolu , Ogun',
    'Alekunifesowapo , Odogbolu , Ogun',
    'Leguru , Odogbolu , Ogun',
    'Ogun Waterside , Ogun',
    'Abigi , Ogun Waterside , Ogun',
    'Ijebu Manuwa , Ogun Waterside , Ogun',
    'Iwopin , Ogun Waterside , Ogun',
    'Ode Omi , Ogun Waterside , Ogun',
    'Remo North , Ogun',
    'Ipokia , Remo North , Ogun',
    'Isala , Remo North , Ogun',
    'Ode Remo , Remo North , Ogun',
    'Ikenne , Remo North , Ogun',
    'Sagamu , Ogun',
    'Ode Lemo , Sagamu , Ogun',
    'Sagamu , Sagamu , Ogun',
    'Yewa , Ogun',
    'Yewa North , Yewa , Ogun',
    'Yewa South , Yewa , Ogun',
    'Imeko Afon , Yewa , Ogun',
    'Oyo',
    'Akinyele , Oyo',
    'Afijio , Oyo',
    'Egbeda , Oyo',
    'Ibadan , Oyo',
    'Apata , Ibadan , Oyo',
    'Old Iyanru/Ijanagang , Ibadan , Oyo',
    'Ibadan polytechnic/ University of Ibadan , Ibadan , Oyo',
    'Bodija , Ibadan , Oyo',
    'Adamasingba , Ibadan , Oyo',
    'Ring Rd , Ibadan , Oyo',
    'Salvation army , Ibadan , Oyo',
    'Yemetu , Ibadan , Oyo',
    'Iwo Rd , Ibadan , Oyo',
    'Basorun , Ibadan , Oyo',
    'Agodi , Ibadan , Oyo',
    'Odinjo , Ibadan , Oyo',
    'Odo ona , Ibadan , Oyo',
    'Oke ado , Ibadan , Oyo',
    'Challenge , Ibadan , Oyo',
    'Molete , Ibadan , Oyo',
    'Olomi , Ibadan , Oyo',
    'Odo Oba , Ibadan , Oyo',
    'Jericho , Ibadan , Oyo',
    'Idishin , Ibadan , Oyo',
    'Alalubosa , Ibadan , Oyo',
    'Ajibode , Ibadan , Oyo',
    'Moniya , Ibadan , Oyo',
    'Sabo(Ibadan) , Ibadan , Oyo',
    'Samonda , Ibadan , Oyo',
    'Oluyole Estate , Ibadan , Oyo',
    'Akala Express , Ibadan , Oyo',
    'Iyanganku , Ibadan , Oyo',
    'Adeoyo , Ibadan , Oyo',
    'Ibadan north west , Ibadan , Oyo',
    'Soka , Ibadan , Oyo',
    'Alakia , Ibadan , Oyo',
    'Eleyele , Ibadan , Oyo',
    'Ojoo , Ibadan , Oyo',
    'Ijaiye Orile , Ibadan , Oyo',
    'Akobo , Ibadan , Oyo',
    'Omi Adio , Ibadan , Oyo',
    'Ibarapa , Oyo',
    'Ido , Oyo',
    'Irepo , Oyo',
    'Iseyin , Oyo',
    'Kajola , Oyo',
    'Lagelu , Oyo',
    'Olode , Lagelu , Oyo',
    'Ejioku , Lagelu , Oyo',
    'Ile Igbon , Lagelu , Oyo',
    'Ariku , Lagelu , Oyo',
    'Lagun , Lagelu , Oyo',
    'Aromona , Lagelu , Oyo',
    'Offa-Igbo , Lagelu , Oyo',
    'Ogunremi , Lagelu , Oyo',
    'Ogunsina , Lagelu , Oyo',
    'Olorunda , Lagelu , Oyo',
    'Monatan , Lagelu , Oyo',
    'Oyedeji , Lagelu , Oyo',
    'Kutayi , Lagelu , Oyo',
    'Sagbe , Lagelu , Oyo',
    'Ogbomosho , Oyo',
    'Oyo , Oyo',
    'Atiba , Oyo',
    'Atisbo , Oyo',
    'Itesiwaju , Oyo',
    'Iwajowa , Oyo',
    'Surulere(Oyo) , Oyo',
    'Anambra',
    'Aguata , Anambra',
    'Anambra East , Anambra',
    'Anambra West , Anambra',
    'Anaocha , Anambra',
    'Awka North , Anambra',
    'Awka South , Anambra',
    'Ayamelum , Anambra',
    'Dunukofia , Anambra',
    'Ekwusigo , Anambra',
    'Idemili North , Anambra',
    'Idemili south , Anambra',
    'Ihiala , Anambra',
    'Njikoka , Anambra',
    'Nnewi North , Anambra',
    'Nnewi South , Anambra',
    'Ogbaru , Anambra',
    'Onitsha North , Anambra',
    'Onitsha South , Anambra',
    'Orumba North , Anambra',
    'Orumba South , Anambra',
    'Oyi , Anambra',
    'Anambra , Anambra',
    'Enugu',
    'Igbo-Eze South , Enugu',
    'Nkanu , Enugu',
    'Udi Agwu , Enugu',
    'Oji-River , Enugu',
    'Ezeagu , Enugu',
    'IgboEze North , Enugu',
    'Isi-Uzo , Enugu',
    'Nsukka , Enugu',
    'Igbo-Ekiti , Enugu',
    'Uzo-Uwani , Enugu',
    'Aninri , Enugu',
    'Nkanu East , Enugu',
    'Udenu , Enugu',
    'Enugu , Enugu',
    'Akwa Ibom',
    'Abak , Akwa Ibom',
    'Eastern Obolo , Akwa Ibom',
    'Eket , Akwa Ibom',
    'Esit Eket , Akwa Ibom',
    'Essien Udim , Akwa Ibom',
    'Etim Ekpo , Akwa Ibom',
    'Etinan , Akwa Ibom',
    'Ibeno , Akwa Ibom',
    'Ibesikpo Asutan , Akwa Ibom',
    'Ibiono Ibom , Akwa Ibom',
    'Ika , Akwa Ibom',
    'Ikono , Akwa Ibom',
    'Ikot Abasi , Akwa Ibom',
    'Ikot Ekpene , Akwa Ibom',
    'Ini , Akwa Ibom',
    'Itu , Akwa Ibom',
    'Mbo , Akwa Ibom',
    'Mkpat Enin , Akwa Ibom',
    'Nsit Atai , Akwa Ibom',
    'Nsit Ibom , Akwa Ibom',
    'Nsit Ubium , Akwa Ibom',
    'Obot Akara , Akwa Ibom',
    'Okobo , Akwa Ibom',
    'Onna , Akwa Ibom',
    'Oron , Akwa Ibom',
    'Oruk Anam , Akwa Ibom',
    'Udung Uko , Akwa Ibom',
    'Ukanafun , Akwa Ibom',
    'Uruan , Akwa Ibom',
    'Urue-Offong/Oruko , Akwa Ibom',
    'Uyo , Akwa Ibom',
    'Adamawa',
    'Demsa , Adamawa',
    'Fufore , Adamawa',
    'Ganaye , Adamawa',
    'Gireri , Adamawa',
    'Gombi , Adamawa',
    'Guyuk , Adamawa',
    'Hong , Adamawa',
    'Jada , Adamawa',
    'Lamurde , Adamawa',
    'Madagali , Adamawa',
    'Maiha , Adamawa',
    'Mayo-Belwa , Adamawa',
    'Michika , Adamawa',
    'Mubi North , Adamawa',
    'Mubi South , Adamawa',
    'Numan , Adamawa',
    'Shelleng , Adamawa',
    'Song , Adamawa',
    'Toungo , Adamawa',
    'Yola North , Adamawa',
    'Yola South , Adamawa',
    'Abia',
    'Aba South , Abia',
    'Arochukwu , Abia',
    'Bende , Abia',
    'Ikwuano , Abia',
    'Isiala-Ngwa North , Abia',
    'Isiala-Ngwa South , Abia',
    'Isuikwato , Abia',
    'Obi Nwa , Abia',
    'Ohafia , Abia',
    'Osisioma , Abia',
    'Ngwa , Abia',
    'Ugwunagbo , Abia',
    'Ukwa East , Abia',
    'Ukwa West , Abia',
    'Umuahia North , Abia',
    'Umuahia South , Abia',
    'Umu-Neochi , Abia',
    'Aba , Abia',
    'Bauchi',
    'Alkaleri , Bauchi',
    'Bauchi , Bauchi',
    'Bogoro , Bauchi',
    'Damban , Bauchi',
    'Darazo , Bauchi',
    'Dass , Bauchi',
    'Ganjuwa , Bauchi',
    'Giade , Bauchi',
    'Itas/Gadau , Bauchi',
    "Jama'are , Bauchi",
    'Katagum , Bauchi',
    'Kirfi , Bauchi',
    'Misau , Bauchi',
    'Ningi , Bauchi',
    'Shira , Bauchi',
    'Tafawa-Balewa , Bauchi',
    'Toro , Bauchi',
    'Warji , Bauchi',
    'Zaki , Bauchi',
    'Bayelsa',
    'Brass , Bayelsa',
    'Ekeremor , Bayelsa',
    'Kolokuma/Opokuma , Bayelsa',
    'Nembe , Bayelsa',
    'Ogbia , Bayelsa',
    'Sagbama , Bayelsa',
    'Southern Jaw , Bayelsa',
    'Yenegoa , Bayelsa',
    'Benue',
    'Ado , Benue',
    'Agatu , Benue',
    'Apa , Benue',
    'Buruku , Benue',
    'Gboko , Benue',
    'Guma , Benue',
    'Gwer East , Benue',
    'Gwer West , Benue',
    'Katsina-Ala , Benue',
    'Konshisha , Benue',
    'Kwande , Benue',
    'Logo , Benue',
    'Makurdi , Benue',
    'Obi , Benue',
    'Ogbadibo , Benue',
    'Oju , Benue',
    'Okpokwu , Benue',
    'Ohimini , Benue',
    'Oturkpo , Benue',
    'Tarka , Benue',
    'Ukum , Benue',
    'Ushongo , Benue',
    'Vandeikya , Benue',
    'Borno',
    'Abadam , Borno',
    'Askira/Uba , Borno',
    'Bama , Borno',
    'Bayo , Borno',
    'Biu , Borno',
    'Chibok , Borno',
    'Damboa , Borno',
    'Dikwa , Borno',
    'Gubio , Borno',
    'Guzamala , Borno',
    'Gwoza , Borno',
    'Hawul , Borno',
    'Jere , Borno',
    'Kaga , Borno',
    'Kala/Balge , Borno',
    'Konduga , Borno',
    'Kukawa , Borno',
    'Kwaya Kusar , Borno',
    'Mafa , Borno',
    'Magumeri , Borno',
    'Maiduguri , Borno',
    'Marte , Borno',
    'Mobbar , Borno',
    'Monguno , Borno',
    'Ngala , Borno',
    'Nganzai , Borno',
    'Shani , Borno',
    'Cross River',
    'Akpabuyo , Cross River',
    'Odukpani , Cross River',
    'Akamkpa , Cross River',
    'Biase , Cross River',
    'Abi , Cross River',
    'Ikom , Cross River',
    'Yarkur , Cross River',
    'Odubra , Cross River',
    'Boki , Cross River',
    'Ogoja , Cross River',
    'Yala , Cross River',
    'Obanliku , Cross River',
    'Obudu , Cross River',
    'Etung , Cross River',
    'Bekwara , Cross River',
    'Bakassi , Cross River',
    'Calabar , Cross River',
    'Delta',
    'Oshimili , Delta',
    'Aniocha , Delta',
    'Aniocha South , Delta',
    'Ika South , Delta',
    'Ika North-East , Delta',
    'Ndokwa West , Delta',
    'Ndokwa East , Delta',
    'Isoko south , Delta',
    'Isoko North , Delta',
    'Bomadi , Delta',
    'Burutu , Delta',
    'Ughelli South , Delta',
    'Ughelli North , Delta',
    'Ethiope West , Delta',
    'Ethiope East , Delta',
    'Sapele , Delta',
    'Okpe , Delta',
    'Uvwie , Delta',
    'Udu , Delta',
    'Ukwani , Delta',
    'Oshimili North , Delta',
    'Patani , Delta',
    'Asaba , Delta',
    'Warri , Delta',
    'Ebonyi',
    'Onicha , Ebonyi',
    'Ohaozara , Ebonyi',
    'Abakaliki , Ebonyi',
    'Ishielu , Ebonyi',
    'lkwo , Ebonyi',
    'Ezza , Ebonyi',
    'Ezza South , Ebonyi',
    'Ohaukwu , Ebonyi',
    'Ebonyi , Ebonyi',
    'Ivo , Ebonyi',
    'Afikpo , Ebonyi',
    'Edo',
    'Esan North-East , Edo',
    'Esan Central , Edo',
    'Esan West , Edo',
    'Egor , Edo',
    'Ukpoba , Edo',
    'Central , Edo',
    'Etsako Central , Edo',
    'Igueben , Edo',
    'Oredo , Edo',
    'Ovia SouthWest , Edo',
    'Ovia South-East , Edo',
    'Orhionwon , Edo',
    'Uhunmwonde , Edo',
    'Etsako East , Edo',
    'Esan South-East , Edo',
    'Etsako West , Edo',
    'Ekiti',
    'Ekiti-East , Ekiti',
    'Ekiti-West , Ekiti',
    'Emure/Ise/Orun , Ekiti',
    'Ekiti South-West , Ekiti',
    'Ikare , Ekiti',
    'Irepodun-Ekiti , Ekiti',
    'Ijero , Ekiti',
    'Ido/Osi , Ekiti',
    'Oye , Ekiti',
    'Ikole , Ekiti',
    'Moba , Ekiti',
    'Gbonyin , Ekiti',
    'Efon , Ekiti',
    'Ise/Orun , Ekiti',
    'Ilejemeje , Ekiti',
    'Ado-Ekiti , Ekiti',
    'Gombe',
    'Akko , Gombe',
    'Balanga , Gombe',
    'Billiri , Gombe',
    'Dukku , Gombe',
    'Kaltungo , Gombe',
    'Kwami , Gombe',
    'Shomgom , Gombe',
    'Funakaye , Gombe',
    'Gombe , Gombe',
    'Nafada/Bajoga , Gombe',
    'Yamaltu/Delta , Gombe',
    'Imo',
    'Aboh-Mbaise , Imo',
    'Ahiazu-Mbaise , Imo',
    'Ehime-Mbano , Imo',
    'Ezinihitte , Imo',
    'Ideato North , Imo',
    'Ideato South , Imo',
    'Ihitte/Uboma , Imo',
    'Ikeduru , Imo',
    'Isiala Mbano , Imo',
    'Isu , Imo',
    'Mbaitoli , Imo',
    'Ngor-Okpala , Imo',
    'Njaba , Imo',
    'Nwangele , Imo',
    'Nkwerre , Imo',
    'Obowo , Imo',
    'Oguta , Imo',
    'Ohaji/Egbema , Imo',
    'Okigwe , Imo',
    'Orlu , Imo',
    'Orsu , Imo',
    'Oru East , Imo',
    'Oru West , Imo',
    'Owerri , Imo',
    'Jigawa',
    'Auyo , Jigawa',
    'Babura , Jigawa',
    'Birni Kudu , Jigawa',
    'Biriniwa , Jigawa',
    'Buji , Jigawa',
    'Dutse , Jigawa',
    'Gagarawa , Jigawa',
    'Garki , Jigawa',
    'Gumel , Jigawa',
    'Guri , Jigawa',
    'Gwaram , Jigawa',
    'Gwiwa , Jigawa',
    'Hadejia , Jigawa',
    'Jahun , Jigawa',
    'Kafin Hausa , Jigawa',
    'Kaugama Kazaure , Jigawa',
    'Kiri Kasamma , Jigawa',
    'Kiyawa , Jigawa',
    'Maigatari , Jigawa',
    'Malam Madori , Jigawa',
    'Miga , Jigawa',
    'Ringim , Jigawa',
    'Roni , Jigawa',
    'Sule-Tankarkar , Jigawa',
    'Taura , Jigawa',
    'Yankwashi , Jigawa',
    'Kaduna',
    'Birni-Gwari , Kaduna',
    'Chikun , Kaduna',
    'Giwa , Kaduna',
    'Igabi , Kaduna',
    'Ikara , Kaduna',
    'jaba , Kaduna',
    "Jema'a , Kaduna",
    'Kachia , Kaduna',
    'Kaduna North , Kaduna',
    'Kaduna South , Kaduna',
    'Kagarko , Kaduna',
    'Kajuru , Kaduna',
    'Kaura , Kaduna',
    'Kauru , Kaduna',
    'Kubau , Kaduna',
    'Kudan , Kaduna',
    'Lere , Kaduna',
    'Makarfi , Kaduna',
    'Sabon-Gari , Kaduna',
    'Sanga , Kaduna',
    'Soba , Kaduna',
    'Zango-Kataf , Kaduna',
    'Zaria , Kaduna',
    'Kano',
    'Ajingi , Kano',
    'Albasu , Kano',
    'Bagwai , Kano',
    'Bebeji , Kano',
    'Bichi , Kano',
    'Bunkure , Kano',
    'Dala , Kano',
    'Dambatta , Kano',
    'Dawakin Kudu , Kano',
    'Dawakin Tofa , Kano',
    'Doguwa , Kano',
    'Fagge , Kano',
    'Gabasawa , Kano',
    'Garko , Kano',
    'Garum , Kano',
    'Mallam , Kano',
    'Gaya , Kano',
    'Gezawa , Kano',
    'Gwale , Kano',
    'Gwarzo , Kano',
    'Kabo , Kano',
    'Kano Municipal , Kano',
    'Karaye , Kano',
    'Kibiya , Kano',
    'Kiru , Kano',
    'kumbotso , Kano',
    'Kunchi , Kano',
    'Kura , Kano',
    'Madobi , Kano',
    'Makoda , Kano',
    'Minjibir , Kano',
    'Nasarawa , Kano',
    'Rano , Kano',
    'Rimin Gado , Kano',
    'Rogo , Kano',
    'Shanono , Kano',
    'Sumaila , Kano',
    'Takali , Kano',
    'Tarauni , Kano',
    'Tofa , Kano',
    'Tsanyawa , Kano',
    'Tudun Wada , Kano',
    'Ungogo , Kano',
    'Warawa , Kano',
    'Wudil , Kano',
    'Katsina',
    'Bakori , Katsina',
    'Batagarawa , Katsina',
    'Batsari , Katsina',
    'Baure , Katsina',
    'Bindawa , Katsina',
    'Charanchi , Katsina',
    'Dandume , Katsina',
    'Danja , Katsina',
    'Dan Musa , Katsina',
    'Daura , Katsina',
    'Dutsi , Katsina',
    'Dutsin-Ma , Katsina',
    'Faskari , Katsina',
    'Funtua , Katsina',
    'Ingawa , Katsina',
    'Jibia , Katsina',
    'Kafur , Katsina',
    'Kaita , Katsina',
    'Kankara , Katsina',
    'Kankia , Katsina',
    'Katsina , Katsina',
    'Kurfi , Katsina',
    'Kusada , Katsina',
    "Mai'Adua , Katsina",
    'Malumfashi , Katsina',
    'Mani , Katsina',
    'Mashi , Katsina',
    'Matazuu , Katsina',
    'Musawa , Katsina',
    'Rimi , Katsina',
    'Sabuwa , Katsina',
    'Safana , Katsina',
    'Sandamu , Katsina',
    'Zango , Katsina',
    'Kebbi',
    'Aleiro , Kebbi',
    'Arewa-Dandi , Kebbi',
    'Argungu , Kebbi',
    'Augie , Kebbi',
    'Bagudo , Kebbi',
    'Birnin Kebbi , Kebbi',
    'Bunza , Kebbi',
    'Dandi , Kebbi',
    'Fakai , Kebbi',
    'Gwandu , Kebbi',
    'Jega , Kebbi',
    'Kalgo , Kebbi',
    'Koko/Besse , Kebbi',
    'Maiyama , Kebbi',
    'Ngaski , Kebbi',
    'Sakaba , Kebbi',
    'Shanga , Kebbi',
    'Suru , Kebbi',
    'Wasagu/Danko , Kebbi',
    'Yauri , Kebbi',
    'Zuru , Kebbi',
    'Kogi',
    'Adavi , Kogi',
    'Ajaokuta , Kogi',
    'Ankpa , Kogi',
    'Bassa , Kogi',
    'Dekina , Kogi',
    'Ibaji , Kogi',
    'Idah , Kogi',
    'Igalamela-Odolu , Kogi',
    'Ijumu , Kogi',
    'Kabba/Bunu , Kogi',
    'Kogi , Kogi',
    'Lokoja , Kogi',
    'Mopa-Muro , Kogi',
    'Ofu , Kogi',
    'Ogori/Mangongo , Kogi',
    'Okehi , Kogi',
    'Okene , Kogi',
    'Olamabolo , Kogi',
    'Omala , Kogi',
    'Yagba East , Kogi',
    'Yagba West , Kogi',
    'Kwara',
    'Asa , Kwara',
    'Baruten , Kwara',
    'Edu , Kwara',
    'Ekiti , Kwara',
    'Ifelodun , Kwara',
    'Isin , Kwara',
    'Kaiama , Kwara',
    'Moro , Kwara',
    'Offa , Kwara',
    'Oke-Ero , Kwara',
    'Oyun , Kwara',
    'Pategi , Kwara',
    'Irepodun , Kwara',
    'Ilorin , Kwara',
    'Nassarawa',
    'Akwanga , Nassarawa',
    'Awe , Nassarawa',
    'Doma , Nassarawa',
    'Karu , Nassarawa',
    'Keana , Nassarawa',
    'Keffi , Nassarawa',
    'Kokona , Nassarawa',
    'Lafia , Nassarawa',
    'Nasarawa-Eggon , Nassarawa',
    'Toto , Nassarawa',
    'Wamba , Nassarawa',
    'Obi-Nassarawa , Nassarawa',
    'Niger',
    'Agaie , Niger',
    'Agwara , Niger',
    'Bida , Niger',
    'Borgu , Niger',
    'Bosso , Niger',
    'Chanchaga , Niger',
    'Edati , Niger',
    'Gbako , Niger',
    'Gurara , Niger',
    'Katcha , Niger',
    'Kontagora , Niger',
    'Lapai , Niger',
    'Lavun , Niger',
    'Magama , Niger',
    'Mariga , Niger',
    'Mashegu , Niger',
    'Mokwa , Niger',
    'Muya , Niger',
    'Pailoro , Niger',
    'Rafi , Niger',
    'Rijau , Niger',
    'Shiroro , Niger',
    'Suleja , Niger',
    'Tafa , Niger',
    'Wushishi , Niger',
    'Ondo',
    'Ese-Odo , Ondo',
    'Idanre , Ondo',
    'Ifedore , Ondo',
    'Ilaje , Ondo',
    'Ile-Oluji , Ondo',
    'Okeigbo , Ondo',
    'Irele , Ondo',
    'Odigbo , Ondo',
    'Okitipupa , Ondo',
    'Ondo East , Ondo',
    'Ondo West , Ondo',
    'Ose , Ondo',
    'Owo , Ondo',
    'Akure , Ondo',
    'Akoko , Ondo',
    'Osun',
    'Aiyedade , Osun',
    'Aiyedire , Osun',
    'Atakumosa East , Osun',
    'Atakumosa West , Osun',
    'Boluwaduro , Osun',
    'Boripe , Osun',
    'Ede North , Osun',
    'Ede South , Osun',
    'Egbedore , Osun',
    'Ife Central , Osun',
    'Ife East , Osun',
    'Ife North , Osun',
    'Ife South , Osun',
    'Ifedayo , Osun',
    'Ila , Osun',
    'Ilesha East , Osun',
    'Ilesha West , Osun',
    'Irewole , Osun',
    'Isokan , Osun',
    'Iwo , Osun',
    'Obokun , Osun',
    'Odo-Otin , Osun',
    'Ola-Oluwa , Osun',
    'Olorunda , Osun',
    'Oriade , Osun',
    'Orolu , Osun',
    'Osogbo , Osun',
    'Irepodun-Osun , Osun',
    'Plateau',
    'Barikin Ladi , Plateau',
    'Bokkos , Plateau',
    'Jos East , Plateau',
    'Jos North , Plateau',
    'Jos South , Plateau',
    'Kanam , Plateau',
    'Kanke , Plateau',
    'Langtang North , Plateau',
    'Langtang South , Plateau',
    'Mangu , Plateau',
    'Mikang , Plateau',
    'Pankshin , Plateau',
    "Qua'an Pan , Plateau",
    'Riyom , Plateau',
    'Shendam , Plateau',
    'Wase , Plateau',
    'Bassa-Plateau , Plateau',
    'Sokoto',
    'Binji , Sokoto',
    'Bodinga , Sokoto',
    'Dange-shnsi , Sokoto',
    'Gada , Sokoto',
    'Goronyo , Sokoto',
    'Gudu , Sokoto',
    'Gawabawa , Sokoto',
    'Illela , Sokoto',
    'Isa , Sokoto',
    'Kware , Sokoto',
    'kebbe , Sokoto',
    'Rabah , Sokoto',
    'Sabon birni , Sokoto',
    'Shagari , Sokoto',
    'Silame , Sokoto',
    'Sokoto North , Sokoto',
    'Sokoto South , Sokoto',
    'Tambuwal , Sokoto',
    'Tqngaza , Sokoto',
    'Tureta , Sokoto',
    'Wamako , Sokoto',
    'Wurno , Sokoto',
    'Yabo , Sokoto',
    'Taraba',
    'Ardo-kola , Taraba',
    'Bali , Taraba',
    'Donga , Taraba',
    'Gashaka , Taraba',
    'Cassol , Taraba',
    'Ibi , Taraba',
    'Jalingo , Taraba',
    'Karin-Lamido , Taraba',
    'Kurmi , Taraba',
    'Lau , Taraba',
    'Sardauna , Taraba',
    'Takum , Taraba',
    'Ussa , Taraba',
    'Wukari , Taraba',
    'Yorro , Taraba',
    'Zing , Taraba',
    'Yobe',
    'Bade , Yobe',
    'Bursari , Yobe',
    'Damaturu , Yobe',
    'Fika , Yobe',
    'Fune , Yobe',
    'Geidam , Yobe',
    'Gujba , Yobe',
    'Gulani , Yobe',
    'Jakusko , Yobe',
    'Karasuwa , Yobe',
    'Karawa , Yobe',
    'Machina , Yobe',
    'Nangere , Yobe',
    'Nguru Potiskum , Yobe',
    'Tarmua , Yobe',
    'Yunusari , Yobe',
    'Yusufari , Yobe',
    'Zamfara',
    'Anka , Zamfara',
    'Bakura , Zamfara',
    'Birnin Magaji , Zamfara',
    'Bukkuyum , Zamfara',
    'Bungudu , Zamfara',
    'Gummi , Zamfara',
    'Gusau , Zamfara',
    'Namoda , Zamfara',
    'Maradun , Zamfara',
    'Maru , Zamfara',
    'Shinkafi , Zamfara',
    'Talata Mafara , Zamfara',
    'Tsafe , Zamfara',
    'Zurmi , Zamfara',
    'Kaura-Zamfara , Zamfara',
  ];
  
  const kenya = [
    'Mombasa',
    'Nyali , Mombasa',
    'Frere Town , Nyali , Mombasa',
    'Ziwa La Ngombe , Nyali , Mombasa',
    'Mkomani , Nyali , Mombasa',
    'Kongowea , Nyali , Mombasa',
    'Kadzandani , Nyali , Mombasa',
    'Nyali Area , Nyali , Mombasa',
    'Likoni , Mombasa',
    'Likoni , Likoni , Mombasa',
    'Mkomani , Mombasa',
    'Bamburi , Mombasa',
    'Majengo , Mombasa',
    'Shimanzi , Mombasa',
    'Tudor , Mombasa',
    'bofu , Mombasa',
    'Junda , Mombasa',
    'Kipevu , Mombasa',
    'Magogoni , Mombasa',
    'Mji Wa Kale , Mombasa',
    'Mokani , Mombasa',
    'Shanzu , Mombasa',
    'Shimanzi/Ganjoni , Mombasa',
    'Kadzandani , Mombasa',
    'Mikindani , Mombasa',
    'Miritini , Mombasa',
    'Mtongwe , Mombasa',
    'Mwakirunge , Mombasa',
    'Port Reitz , Mombasa',
    'Shika Adabu , Mombasa',
    'Timbwani , Mombasa',
    'Tononoka , Mombasa',
    "Ziwa La Ng'Ombe , Mombasa",
    'Mtwapa , Mombasa',
    'Kizingo , Mombasa',
    'Mombasa Island , Mombasa',
    'Diani , Mombasa',
    'Utange , Mombasa',
    'Bombolulu , Mombasa',
    'Vescon , Mombasa',
    'Nairobi',
    'Westlands , Nairobi',
    'Kitisuru , Westlands , Nairobi',
    'Kangemi , Westlands , Nairobi',
    'Mountain View , Westlands , Nairobi',
    'Riverside , Westlands , Nairobi',
    'General Mathenge , Westlands , Nairobi',
    'Lower Kabete , Westlands , Nairobi',
    'Loresho , Westlands , Nairobi',
    'Spring Valley , Westlands , Nairobi',
    'Nyari , Westlands , Nairobi',
    'Kyuna , Westlands , Nairobi',
    'Gigiri , Westlands , Nairobi',
    'Brookside , Westlands , Nairobi',
    'Waiyaki Way , Westlands , Nairobi',
    'Westlands Area , Westlands , Nairobi',
    'Whispers , Westlands , Nairobi',
    'Lakeview , Westlands , Nairobi',
    'New Kitusuru , Westlands , Nairobi',
    'Parklands , Westlands , Nairobi',
    'Hill View , Westlands , Nairobi',
    'Rosslyn , Westlands , Nairobi',
    'Runda , Westlands , Nairobi',
    'Thigiri , Westlands , Nairobi',
    'Dagoretti North , Nairobi',
    'Kilimani , Dagoretti North , Nairobi',
    'Kawangware , Dagoretti North , Nairobi',
    'Valley Arcade , Dagoretti North , Nairobi',
    'Maziwa , Dagoretti North , Nairobi',
    'Hurlingham , Dagoretti North , Nairobi',
    'Gatina , Dagoretti North , Nairobi',
    'Kileleshwa , Dagoretti North , Nairobi',
    'kabiro , Dagoretti North , Nairobi',
    'Lavington , Dagoretti North , Nairobi',
    'Valley Road , Dagoretti North , Nairobi',
    'State House , Dagoretti North , Nairobi',
    'Dennis Pritt , Dagoretti North , Nairobi',
    'Naivasha Road , Dagoretti North , Nairobi',
    'Dagoretti South , Nairobi',
    "Ngand'o , Dagoretti South , Nairobi",
    'Riruta , Dagoretti South , Nairobi',
    'Highrise , Dagoretti South , Nairobi',
    'Uthiru , Dagoretti South , Nairobi',
    'Waithaka , Dagoretti South , Nairobi',
    'Dagoretti Corner , Dagoretti South , Nairobi',
    'Langata , Nairobi',
    'Karura , Langata , Nairobi',
    'Karen , Langata , Nairobi',
    'Nairobi Hardy , Langata , Nairobi',
    'Nairobi West , Langata , Nairobi',
    'Kibera , Langata , Nairobi',
    'Upper Hill , Langata , Nairobi',
    'South C , Langata , Nairobi',
    'South B , Langata , Nairobi',
    'Madaraka , Langata , Nairobi',
    'Langata Area , Langata , Nairobi',
    'Southlands , Langata , Nairobi',
    'Hillview , Langata , Nairobi',
    'Ngumo Estate , Langata , Nairobi',
    'Roysambu , Nairobi',
    'Githurai , Roysambu , Nairobi',
    'Zimmermann , Roysambu , Nairobi',
    'Roysambu Area , Roysambu , Nairobi',
    'Kahawa , Roysambu , Nairobi',
    'Marurui , Roysambu , Nairobi',
    'Kahawa West , Roysambu , Nairobi',
    'Thome , Roysambu , Nairobi',
    'Kahawa Sukari , Roysambu , Nairobi',
    'Kahawa Soweto , Roysambu , Nairobi',
    'Garden Estate , Roysambu , Nairobi',
    'Kasarani , Nairobi',
    'Clay City , Kasarani , Nairobi',
    'Chereni , Kasarani , Nairobi',
    'Mwiki , Kasarani , Nairobi',
    'Kasarani Area , Kasarani , Nairobi',
    'Njiru , Kasarani , Nairobi',
    'Ngumba Estate , Kasarani , Nairobi',
    'Kagundo Road , Kasarani , Nairobi',
    'Ruai , Kasarani , Nairobi',
    'Ruaraka , Nairobi',
    'Ruaraka , Ruaraka , Nairobi',
    'Embakasi , Nairobi',
    'Embakasi Central , Embakasi , Nairobi',
    'Muthaiga , Nairobi',
    'Muthaiga Area , Muthaiga , Nairobi',
    'Old Muthaiga , Muthaiga , Nairobi',
    'North Muthaiga , Muthaiga , Nairobi',
    'Mirema , Muthaiga , Nairobi',
    'Makadara , Nairobi',
    'Makadara , Makadara , Nairobi',
    'Starehe , Nairobi',
    'Nairobi Central , Starehe , Nairobi',
    'Ngara , Starehe , Nairobi',
    'Pangani , Starehe , Nairobi',
    'Ziwani/Kariokor , Starehe , Nairobi',
    'Landimawe , Starehe , Nairobi',
    'Nairobi South , Starehe , Nairobi',
    'CBD , Starehe , Nairobi',
    'Mathare , Nairobi',
    'Mathare , Mathare , Nairobi',
    'Mombasa Road , Nairobi',
    'Mombasa Road , Mombasa Road , Nairobi',
    'Kiambu Road , Nairobi',
    'Kiambu Road , Kiambu Road , Nairobi',
    'Thika Road , Nairobi',
    'Thika Road , Thika Road , Nairobi',
    'Ridgeways , Nairobi',
    'Ridgeways , Ridgeways , Nairobi',
    'Kilimani , Nairobi',
    'Lavingtone , Nairobi',
    'Nairobi Central , Nairobi',
    'Ngara , Nairobi',
    'Baba Dogo , Nairobi',
    'California , Nairobi',
    'Githurai , Nairobi',
    'Harambee , Nairobi',
    'Imara Daima , Nairobi',
    'Kahawa North , Nairobi',
    'Kahawa West , Nairobi',
    'Kariobangi North , Nairobi',
    'Kariobangi South , Nairobi',
    'Karura , Nairobi',
    'Kileleshwa , Nairobi',
    'Kitisuru , Nairobi',
    'Komarock , Nairobi',
    'Kwa Njenga , Nairobi',
    'Matopeni , Nairobi',
    'Mlango Kubwa , Nairobi',
    'Mugumo-Ini (Langata) , Nairobi',
    'Mutuini , Nairobi',
    'Mwiki , Nairobi',
    'Nairobi South , Nairobi',
    'Nairobi West , Nairobi',
    'Njiru , Nairobi',
    'Pangani , Nairobi',
    'Parkland , Nairobi',
    'Riruta , Nairobi',
    'Ruai , Nairobi',
    'Upper Savanna , Nairobi',
    'Utawala , Nairobi',
    'Woodley/Kenyatta Golf Course , Nairobi',
    'Zimmerman , Nairobi',
    'Kibera , Nairobi',
    'Matopeni/ Spring Valley , Nairobi',
    'Parklands/Highridge , Nairobi',
    'Umoja , Nairobi',
    'Karen , Nairobi',
    'Airbase , Nairobi',
    'Chokaa , Nairobi',
    'Clay City , Nairobi',
    'Dandora Area I , Nairobi',
    'Dandora Area II , Nairobi',
    'Dandora Area III , Nairobi',
    'Dandora Area IV , Nairobi',
    'Eastleigh North , Nairobi',
    'Eastleigh South , Nairobi',
    'Gatina , Nairobi',
    'Hospital (Matha Re) , Nairobi',
    'Huruma , Nairobi',
    'Kabiro , Nairobi',
    'Kahawa , Nairobi',
    'Kangemi , Nairobi',
    'Kawangware , Nairobi',
    'Kayole Central , Nairobi',
    'Kayole North , Nairobi',
    'Kayole South , Nairobi',
    'Kiamaiko , Nairobi',
    'Korogocho , Nairobi',
    'Kwa Reuben , Nairobi',
    'Kware , Nairobi',
    'Laini Saba , Nairobi',
    'Landimawe , Nairobi',
    'Lindi , Nairobi',
    'Lower Savannah , Nairobi',
    'Lucky Summer , Nairobi',
    'Mabatini , Nairobi',
    'Makina , Nairobi',
    'Makongeni , Nairobi',
    'Maringo/Hamza , Nairobi',
    'Maziwa , Nairobi',
    'Mihango , Nairobi',
    'Mountain View , Nairobi',
    'Mowlem , Nairobi',
    'Ngando , Nairobi',
    'Ngei , Nairobi',
    'Njiru Shopping Centre , Nairobi',
    'Nyayo Highrise , Nairobi',
    'Pipeline , Nairobi',
    'Pumwani , Nairobi',
    'Riruta Satellite , Nairobi',
    "Sarang'Ombe , Nairobi",
    'South C , Nairobi',
    'Umoja II , Nairobi',
    'Utalii , Nairobi',
    'Uthiru/Ruthimitu , Nairobi',
    'Viwandani (Makadara , Nairobi',
    'Waithaka , Nairobi',
    'Ziwani/Kariokor , Nairobi',
    'Lavington , Nairobi',
    'Syokimau , Nairobi',
    'Hurlingham , Nairobi',
    'Joska , Nairobi',
    'Kiamumbi , Nairobi',
    'Peponi , Nairobi',
    'Gigiri , Nairobi',
    'Parklands , Nairobi',
    'Runda , Nairobi',
    'Muthaiga North , Nairobi',
    'Katani , Nairobi',
    'Kahawa Wendani , Nairobi',
    'Riverside , Nairobi',
    'Kerarapon , Nairobi',
    'Redhill , Nairobi',
    'Buruburu , Nairobi',
    'Mombasa Rd , Nairobi',
    'Spring Valley , Nairobi',
    'Madaraka , Nairobi',
    'Ruaka , Nairobi',
    'Rosslyn , Nairobi',
    'Industrial Area , Nairobi',
    'South B , Nairobi',
    'Garden Estate , Nairobi',
    'Ngong Rd , Nairobi',
    'Highridge , Nairobi',
    'Githurai 44 , Nairobi',
    'Lower Kabete , Nairobi',
    'Loresho , Nairobi',
    'Nairobi CBD , Nairobi',
    'Mlolongo , Nairobi',
    'Kahawa sukari , Nairobi',
    'Nyari , Nairobi',
    'Upper Hill , Nairobi',
    'Kyuna , Nairobi',
    'Jamhuri , Nairobi',
    'Donholm , Nairobi',
    'Valley Arcade , Nairobi',
    'Mirema , Nairobi',
    'Ngecha , Nairobi',
    'Fedha , Nairobi',
    'New Muthaiga , Nairobi',
    'Thome , Nairobi',
    'Muthangari , Nairobi',
    'Thigiri , Nairobi',
    'Lamu',
    'Kiambu Town , Lamu',
    'Kiambu Town , Kiambu Town , Lamu',
    'Lamu West , Lamu',
    'Lamu West , Lamu West , Lamu',
    'Lamu East , Lamu',
    'Lamu East , Lamu East , Lamu',
    'Taita-Taveta',
    'Taveta , Taita-Taveta',
    'Wundanyi , Taita-Taveta',
    'Mwatate , Taita-Taveta',
    'Voi , Taita-Taveta',
    'Kwale',
    'Msambweni , Kwale',
    'Diani , Msambweni , Kwale',
    'Dzombo , Msambweni , Kwale',
    'Kikoneni , Msambweni , Kwale',
    'Kingwende , Msambweni , Kwale',
    'Kinondo , Msambweni , Kwale',
    'Mivumoni , Msambweni , Kwale',
    'Msambweni Area , Msambweni , Kwale',
    'Mwereni , Msambweni , Kwale',
    'Pongwe , Msambweni , Kwale',
    'Vanga , Msambweni , Kwale',
    'Gazi , Msambweni , Kwale',
    'Funzi , Msambweni , Kwale',
    'Matuga , Kwale',
    'Matuga , Matuga , Kwale',
    'Kinango , Kwale',
    'Kinango , Kinango , Kwale',
    'Lunga Lunga , Kwale',
    'Lunga Lunga , Lunga Lunga , Kwale',
    'Ukunda , Kwale',
    'Ukunda , Ukunda , Kwale',
    'Nyamira',
    'Borabu , Nyamira',
    'Borabu , Borabu , Nyamira',
    'Kitutu Masaba , Nyamira',
    'Kitutu Masaba , Kitutu Masaba , Nyamira',
    'North Mugirango , Nyamira',
    'North Mugirango , North Mugirango , Nyamira',
    'West Mugirango , Nyamira',
    'West mugirango , West Mugirango , Nyamira',
    'Kilifi',
    'Red Hill , Kilifi',
    'Red hill , Red Hill , Kilifi',
    'Kilifi North , Kilifi',
    'Tezo , Kilifi North , Kilifi',
    'Sokoni , Kilifi North , Kilifi',
    'Kibarani , Kilifi North , Kilifi',
    'Dabaso , Kilifi North , Kilifi',
    'Matsangoni , Kilifi North , Kilifi',
    'Kilifi South , Kilifi',
    'Kilifi South , Kilifi South , Kilifi',
    'Kikambala , Kilifi South , Kilifi',
    'Mtwapa , Kilifi South , Kilifi',
    'Kaloleni , Kilifi',
    'Rabai , Kilifi',
    'Ganza , Kilifi',
    'Malindi , Kilifi',
    'Kakuyuni , Malindi , Kilifi',
    'Jilore , Malindi , Kilifi',
    'Ganda , Malindi , Kilifi',
    'Malindi Town , Malindi , Kilifi',
    'Shella , Malindi , Kilifi',
    'Magarini , Kilifi',
    'Bofa , Kilifi',
    'Vipingo , Kilifi',
    'Kikambala , Kilifi',
    'Kilifi , Kilifi',
    'Bofa Beach , Kilifi',
    'Mazeras , Kilifi',
    'Tana River',
    'Garsen , Tana River',
    'Galole , Tana River',
    'Bura , Tana River',
    'Garissa',
    'Garissa , Garissa',
    'Garissa , Garissa , Garissa',
    'Ijara , Garissa',
    'Ijara , Ijara , Garissa',
    'Balambala , Garissa',
    'Balambala , Balambala , Garissa',
    'Fafi , Garissa',
    'Fafi , Fafi , Garissa',
    'Lagdera , Garissa',
    'Dadaab , Garissa',
    'Dadaab , Dadaab , Garissa',
    'Wajir',
    'Wajir North , Wajir',
    'Wajir West , Wajir',
    'Wajir East , Wajir',
    'Wajir South , Wajir',
    'Mandera',
    'Mandera South , Mandera',
    'Mandera South , Mandera South , Mandera',
    'Mandera West , Mandera',
    'Mandera West , Mandera West , Mandera',
    'Mandera East , Mandera',
    'Mandera East , Mandera East , Mandera',
    'Mandera North , Mandera',
    'Mandera North , Mandera North , Mandera',
    'Banisa , Mandera',
    'Banisa , Banisa , Mandera',
    'Lafey , Mandera',
    'Lafey , Lafey , Mandera',
    'Marsabit',
    'North Horr , Marsabit',
    'North Horr , North Horr , Marsabit',
    'Saku , Marsabit',
    'Saku , Saku , Marsabit',
    'Laisamis , Marsabit',
    'Laisamis , Laisamis , Marsabit',
    'Isiolo',
    'Meru',
    'Igembe South , Meru',
    'Igembe South , Igembe South , Meru',
    'Igembe Central , Meru',
    'Igembe Central , Igembe Central , Meru',
    'Igembe North , Meru',
    'Igemba North , Igembe North , Meru',
    'Tigania West , Meru',
    'Tigania West , Tigania West , Meru',
    'Tigania East , Meru',
    'Tigania East , Tigania East , Meru',
    'North Imenti , Meru',
    'North Imenti , North Imenti , Meru',
    'Central Imenti , Meru',
    'Central Imenti , Central Imenti , Meru',
    'South Imenti , Meru',
    'South Imenti , South Imenti , Meru',
    'Meru , Meru',
    'Tharaka-Nithi',
    'Maara , Tharaka-Nithi',
    "Chuka/ lgambang'ombe , Tharaka-Nithi",
    'Tharaka , Tharaka-Nithi',
    'Embu',
    'Embu East , Embu',
    'Embu East , Embu East , Embu',
    'Mbeere North , Embu',
    'Mbeere North , Mbeere North , Embu',
    'Mbeere South , Embu',
    'Mbeere South , Mbeere South , Embu',
    'Embu West , Embu',
    'Embu West , Embu West , Embu',
    'Embu North , Embu',
    'Embu North , Embu North , Embu',
    'Embu , Embu',
    'Kitui',
    'Kitui West , Kitui',
    'Kitui West , Kitui West , Kitui',
    'Kitui Central , Kitui',
    'kitui Central , Kitui Central , Kitui',
    'Kitui South , Kitui',
    'Kitui South , Kitui South , Kitui',
    'Mutitio , Kitui',
    'Mutitio , Mutitio , Kitui',
    'Mwingi North , Kitui',
    'Mwingi North , Mwingi North , Kitui',
    'Mwingi South , Kitui',
    'Mwingi South , Mwingi South , Kitui',
    'Machakos',
    'Athi RIver , Machakos',
    'Lukenya , Athi RIver , Machakos',
    'Day Star , Athi RIver , Machakos',
    'Mlolongo , Athi RIver , Machakos',
    'Syokimau , Athi RIver , Machakos',
    'Athi River Area , Athi RIver , Machakos',
    'Katani , Athi RIver , Machakos',
    'Masinga Central , Machakos',
    'Masinga , Masinga Central , Machakos',
    'Kangundo Central , Machakos',
    'Kalandini , Kangundo Central , Machakos',
    'Kangundo Area , Kangundo Central , Machakos',
    'Kanzalu , Kangundo Central , Machakos',
    'Kawathei , Kangundo Central , Machakos',
    'Kivaani , Kangundo Central , Machakos',
    'Koma Rock , Kangundo Central , Machakos',
    'Kyanzavi , Kangundo Central , Machakos',
    'Kyeleni , Kangundo Central , Machakos',
    'Nguluni , Kangundo Central , Machakos',
    'Tala , Kangundo Central , Machakos',
    'Joska , Kangundo Central , Machakos',
    'Kamulu , Kangundo Central , Machakos',
    'Matungulu Central , Machakos',
    'Matungulu , Matungulu Central , Machakos',
    'Machakos Central , Machakos',
    'Machakos Town , Machakos Central , Machakos',
    'Makutano/Mwala , Machakos',
    'Mwala , Makutano/Mwala , Machakos',
    'Kangundo East , Machakos',
    'Kangundo North , Machakos',
    'Kangundo West , Machakos',
    'Matungulu East , Machakos',
    'Matungulu North , Machakos',
    'Matungulu West , Machakos',
    'Syokimau/Mulolongo , Machakos',
    'Ekalakala , Machakos',
    'Ikombe , Machakos',
    'Kalama , Machakos',
    'Katangi , Machakos',
    'Kathiani Central , Machakos',
    'Kibauni , Machakos',
    'Kinanie , Machakos',
    'Kithimani , Machakos',
    'Kivaa , Machakos',
    'Kyeleni , Machakos',
    'Lower Kaewa/Kaani , Machakos',
    'Masii , Machakos',
    'Matuu , Machakos',
    'Mbiuni , Machakos',
    'Mitaboni , Machakos',
    'Mua , Machakos',
    'Mumbuni North , Machakos',
    'Muthwani , Machakos',
    'Mutituni , Machakos',
    'Muvuti/Kiima-Kimwe , Machakos',
    'Ndalani , Machakos',
    'Ndithini , Machakos',
    'Tala , Machakos',
    'Upper Kaewa/Iveti , Machakos',
    'Wamunyu , Machakos',
    'Machakos , Machakos',
    'Konza , Machakos',
    'Makueni',
    'Mbooni , Makueni',
    'Mbooni , Mbooni , Makueni',
    'Kilome , Makueni',
    'Kilome , Kilome , Makueni',
    'Kaiti , Makueni',
    'Kaiti , Kaiti , Makueni',
    'Kibwezi West , Makueni',
    'Kibwezi West , Kibwezi West , Makueni',
    'Makueni , Makueni',
    'Makueni , Makueni , Makueni',
    'Emali , Makueni',
    'Nyandarua',
    'Kinangop , Nyandarua',
    'Kinangop , Kinangop , Nyandarua',
    'Kipipiri , Nyandarua',
    'Kipipiri , Kipipiri , Nyandarua',
    'Ol Kalou , Nyandarua',
    'Ol kalou , Ol Kalou , Nyandarua',
    'Ol Joro Orok , Nyandarua',
    'Ol Joro Orok , Ol Joro Orok , Nyandarua',
    'Ndaragwa , Nyandarua',
    'Ndaragwa , Ndaragwa , Nyandarua',
    'Nyandarua , Nyandarua',
    'Nyeri',
    'Tetu , Nyeri',
    'Tetu , Tetu , Nyeri',
    'Kieni , Nyeri',
    'Kieni , Kieni , Nyeri',
    'Mathira , Nyeri',
    'Mathira , Mathira , Nyeri',
    'Othaya , Nyeri',
    'Othaya , Othaya , Nyeri',
    'Mukurweini , Nyeri',
    'Nyeri Town , Nyeri',
    'Nyeri , Nyeri',
    'Kirinyaga',
    'Mwea , Kirinyaga',
    'Mwea , Mwea , Kirinyaga',
    'Gichugu , Kirinyaga',
    'Gichugu , Gichugu , Kirinyaga',
    'Ndia , Kirinyaga',
    'Ndia , Ndia , Kirinyaga',
    'Kirinyaga Central , Kirinyaga',
    'Kirinyaga Central , Kirinyaga Central , Kirinyaga',
    "Murang'a",
    "Kangema , Murang'a",
    "Kangema , Kangema , Murang'a",
    "Kiharu , Murang'a",
    "Kiharu , Kiharu , Murang'a",
    "Mathioya , Murang'a",
    "Mathioya , Mathioya , Murang'a",
    "Kigumo , Murang'a",
    "Kigumo , Kigumo , Murang'a",
    "Kandara , Murang'a",
    "Kandara , Kandara , Murang'a",
    "Maragwa , Murang'a",
    "Maragwa , Maragwa , Murang'a",
    "Gatanga , Murang'a",
    "Gatanga , Gatanga , Murang'a",
    'Kiambu',
    'Githunguri , Kiambu',
    'Githunguri , Githunguri , Kiambu',
    'Thika , Kiambu',
    'Thika , Thika , Kiambu',
    'Ruiru , Kiambu',
    'Ruiru , Ruiru , Kiambu',
    'Lari/Kirenga , Kiambu',
    'Lari , Lari/Kirenga , Kiambu',
    'Kabete , Kiambu',
    'Kabete Area , Kabete , Kiambu',
    'Kikuyu Town , Kabete , Kiambu',
    'Kinoo , Kabete , Kiambu',
    'Wangige , Kabete , Kiambu',
    'Juja , Kiambu',
    'Kikuyu , Kiambu',
    'Ndenderu , Kiambu',
    'Bibirioni , Kiambu',
    'Gatuanyaga , Kiambu',
    'Githiga (Githunguri) , Kiambu',
    'Hospital (Thika) , Kiambu',
    'Kalimoni , Kiambu',
    'Karai , Kiambu',
    'Karuri , Kiambu',
    'Kiganjo , Kiambu',
    'Kijabe , Kiambu',
    'Kinoo , Kiambu',
    'Limuru Central , Kiambu',
    'Limuru East , Kiambu',
    'Muchatha , Kiambu',
    'Muguga , Kiambu',
    'Ndeiya , Kiambu',
    'Ndumberi , Kiambu',
    'Ngecha Tigoni , Kiambu',
    'Sigona , Kiambu',
    'Uthiru , Kiambu',
    'Githobokoni , Kiambu',
    'Gitothua , Kiambu',
    'Gituamba , Kiambu',
    'Ikinu , Kiambu',
    'Kamburu , Kiambu',
    'Kamenu , Kiambu',
    'Kiamwangi , Kiambu',
    'Kihara , Kiambu',
    'Kinale , Kiambu',
    'Kiuu , Kiambu',
    'Komothai , Kiambu',
    "Mang'U , Kiambu",
    'Membley Estate , Kiambu',
    'Murera , Kiambu',
    'Nachu , Kiambu',
    'Ndarugu , Kiambu',
    'Ngenda , Kiambu',
    'Ngewa , Kiambu',
    'Ngoliba , Kiambu',
    'Nyadhuna , Kiambu',
    'Nyanduma , Kiambu',
    'Riabai , Kiambu',
    'Theta , Kiambu',
    "Ting'Ang'A , Kiambu",
    'Township C , Kiambu',
    'Township E , Kiambu',
    'Witeithie , Kiambu',
    'Kiambu , Kiambu',
    'Turkana',
    'Turkana North , Turkana',
    'Turkana Central , Turkana',
    'Turkana South , Turkana',
    'West Pokot',
    'Kacheliba , West Pokot',
    'Kapenguria , West Pokot',
    'Sigor , West Pokot',
    'Pokot South , West Pokot',
    'Samburu',
    'Samburu East , Samburu',
    'Samburu North , Samburu',
    'Samburu Central , Samburu',
    'Trans Nzoia',
    'Cherangany , Trans Nzoia',
    'kwanza , Trans Nzoia',
    'Saboti , Trans Nzoia',
    'Endebess , Trans Nzoia',
    'Kiminini , Trans Nzoia',
    'Uasin Gishu',
    'Eldoret East , Uasin Gishu',
    'Eldoret North , Uasin Gishu',
    'Eldoret South , Uasin Gishu',
    'Elgeyo-Marakwet',
    'Iten , Elgeyo-Marakwet',
    'Marakwet East , Elgeyo-Marakwet',
    'Marakwet East , Marakwet East , Elgeyo-Marakwet',
    'Marakwet West , Elgeyo-Marakwet',
    'Marakwet West , Marakwet West , Elgeyo-Marakwet',
    'Keiyo North , Elgeyo-Marakwet',
    'Keiyo North , Keiyo North , Elgeyo-Marakwet',
    'Keiyo South , Elgeyo-Marakwet',
    'keiyo South , Keiyo South , Elgeyo-Marakwet',
    'Nandi',
    'Mosop , Nandi',
    'Mosop , Mosop , Nandi',
    'Emgwen , Nandi',
    'Emgwen , Emgwen , Nandi',
    'Aldai , Nandi',
    'Aldai , Aldai , Nandi',
    'Tinderet , Nandi',
    'Tinderet , Tinderet , Nandi',
    'Nandi Hills , Nandi',
    'Nandi Hills , Nandi Hills , Nandi',
    'Chesumei , Nandi',
    'Chesumei , Chesumei , Nandi',
    'Baringo',
    'Mogoti , Baringo',
    'Mogoti , Mogoti , Baringo',
    'Kabarnet , Baringo',
    'kabarnet , Kabarnet , Baringo',
    'Kabartonjo , Baringo',
    'Kimilili , Kabartonjo , Baringo',
    'Kabartonjo , Kabartonjo , Baringo',
    'Eldama Ravine , Baringo',
    'Eldama Ravine , Eldama Ravine , Baringo',
    'Marigat , Baringo',
    'Marigat , Marigat , Baringo',
    'Chemolingot , Baringo',
    'Chemolingot , Chemolingot , Baringo',
    'Laikipia',
    'Laikipa East , Laikipia',
    'Hospital , Laikipa East , Laikipia',
    'Biashara , Laikipa East , Laikipia',
    'Central , Laikipa East , Laikipia',
    'Mashmaba , Laikipa East , Laikipia',
    'Nturukuma , Laikipa East , Laikipia',
    'Ethi , Laikipa East , Laikipia',
    'Lidigiri , Laikipa East , Laikipia',
    'Liingwesi , Laikipa East , Laikipia',
    'Lamuria , Laikipa East , Laikipia',
    'Makurian , Laikipa East , Laikipia',
    'Mukogodo , Laikipa East , Laikipia',
    'Mumonyot , Laikipa East , Laikipia',
    'Naibor , Laikipa East , Laikipia',
    'Oloiborsoit , Laikipa East , Laikipia',
    'Segera , Laikipa East , Laikipia',
    'Sirma , Laikipa East , Laikipia',
    'Tigithi , Laikipa East , Laikipia',
    'Umande , Laikipa East , Laikipia',
    'Nanyuki , Laikipa East , Laikipia',
    'Noru moru , Laikipa East , Laikipia',
    'Rumuruti , Laikipa East , Laikipia',
    'Laikipia West , Laikipia',
    'Laikipia West , Laikipia West , Laikipia',
    'Biashara , Laikipia',
    'Laikipia , Laikipia',
    'Nakuru',
    'Molo , Nakuru',
    'Molo , Molo , Nakuru',
    'Rongai , Nakuru',
    'Boror , Rongai , Nakuru',
    'Kampi Ya Moto , Rongai , Nakuru',
    'Lenginet , Rongai , Nakuru',
    'Maji Tamu , Rongai , Nakuru',
    'Makongeni , Rongai , Nakuru',
    'Ngata , Rongai , Nakuru',
    'Rongai Area , Rongai , Nakuru',
    'Solai , Rongai , Nakuru',
    'Waseges , Rongai , Nakuru',
    'Kiamunyi , Rongai , Nakuru',
    'Subukia , Nakuru',
    'Subukia , Subukia , Nakuru',
    'Njoro , Nakuru',
    'Njoro , Njoro , Nakuru',
    'Gilgil , Nakuru',
    'Gilgil , Gilgil , Nakuru',
    'Bahati , Nakuru',
    'Bahati , Bahati , Nakuru',
    'Lanet/Umoja , Nakuru',
    'London , Nakuru',
    'Naivasha East , Nakuru',
    'Nakuru East , Nakuru',
    'Amalo , Nakuru',
    'Biashara (Naivasha) , Nakuru',
    'Dundori , Nakuru',
    'Elburgon , Nakuru',
    'Elementaita , Nakuru',
    'Flamingo , Nakuru',
    'Hells Gate , Nakuru',
    'Kabatini , Nakuru',
    'Kabazi , Nakuru',
    'Kamara , Nakuru',
    'Kapkures (Nakuru) , Nakuru',
    'Keringet , Nakuru',
    'Kiamaina , Nakuru',
    'Kihingo , Nakuru',
    'Kiptagich , Nakuru',
    'Kiptororo , Nakuru',
    'Lare , Nakuru',
    'Mai Mahiu , Nakuru',
    'Maiella , Nakuru',
    'Malewa West , Nakuru',
    'Mariashoni , Nakuru',
    'Mau Narok , Nakuru',
    'Mauche , Nakuru',
    'Mbaruk/Eburu , Nakuru',
    'Menengai West , Nakuru',
    'Nyota , Nakuru',
    'Olkaria , Nakuru',
    'Rhoda , Nakuru',
    'Sirikwa , Nakuru',
    'Soin (Rongai) , Nakuru',
    'Solai , Nakuru',
    'Tinet , Nakuru',
    'Turi , Nakuru',
    'Visoi , Nakuru',
    'Viwandani (Naivasha) , Nakuru',
    'Waseges , Nakuru',
    'Nakuru Town , Nakuru',
    'Narok',
    'Narok North , Narok',
    'Narok North , Narok North , Narok',
    'Narok South , Narok',
    'Narok South , Narok South , Narok',
    'Narok East , Narok',
    'Narok East , Narok East , Narok',
    'Narok West , Narok',
    'Narok West , Narok West , Narok',
    'Emurua Dikirr , Narok',
    'Emurua Dikirr , Emurua Dikirr , Narok',
    'Narok , Narok',
    'Mara , Narok',
    'Kajiado',
    'Ngong , Kajiado',
    'Jamhuri , Ngong , Kajiado',
    'Kangawa Zone , Ngong , Kajiado',
    'Kimbo Zone , Ngong , Kajiado',
    'Riara , Ngong , Kajiado',
    'Shade Zone , Ngong , Kajiado',
    'Sub Zone , Ngong , Kajiado',
    'Ngong Road , Kajiado',
    'Ngong Road , Ngong Road , Kajiado',
    'Kitengela , Kajiado',
    'Ongata Rongai , Kajiado',
    'Iloodokilani , Kajiado',
    'Kaputiei North , Kajiado',
    'Kimana , Kajiado',
    'Magadi , Kajiado',
    'Dalalekutuk , Kajiado',
    'Entonet/Lenkisim , Kajiado',
    "Ewuaso Oonkidong'I , Kajiado",
    'Ildamat (Kajiado) , Kajiado',
    'Imaroro , Kajiado',
    "Ewuaso Oonkidong' , Kajiado",
    'Keekonyokie (Kajiado) , Kajiado',
    'Kenyawa-Poka , Kajiado',
    'Kuku , Kajiado',
    'Matapato North , Kajiado',
    'Matapato South , Kajiado',
    'Mbirikani/Eselenkei , Kajiado',
    'Mosiro (Kajiado) , Kajiado',
    'Nkaimurunya , Kajiado',
    'Olkeri , Kajiado',
    'Oloolua , Kajiado',
    'Oloosirkon/Sholinke , Kajiado',
    'Purko , Kajiado',
    'Rombo , Kajiado',
    'Kajiado , Kajiado',
    'Tuala , Kajiado',
    'Kericho',
    'Kipkelion , Kericho',
    'Kipkelion , Kipkelion , Kericho',
    'Bureti , Kericho',
    'Bureti , Bureti , Kericho',
    'Belgut , Kericho',
    'Belgut , Belgut , Kericho',
    'Ainamoi , Kericho',
    'Ainamoi , Ainamoi , Kericho',
    'Bomet',
    'Chepalungu , Bomet',
    'Chepalungu , Chepalungu , Bomet',
    'Bomet , Bomet',
    'Bomet , Bomet , Bomet',
    'Konoin , Bomet',
    'Konoin , Konoin , Bomet',
    'Sotik , Bomet',
    'Sotik , Sotik , Bomet',
    'Kakamega',
    'Mumias , Kakamega',
    'Mumias , Mumias , Kakamega',
    'Matungu , Kakamega',
    'Matungu , Matungu , Kakamega',
    'Butere , Kakamega',
    'Butere , Butere , Kakamega',
    'Ikolomani , Kakamega',
    'Ikolomani , Ikolomani , Kakamega',
    'Shinyalu , Kakamega',
    'Shinyalu , Shinyalu , Kakamega',
    'Khwisero , Kakamega',
    'Lagdera , Khwisero , Kakamega',
    'Khwisero , Khwisero , Kakamega',
    'Lurambi , Kakamega',
    'Lurambi , Lurambi , Kakamega',
    'Lugari , Kakamega',
    'Lugari , Lugari , Kakamega',
    'Malava , Kakamega',
    'Malava , Malava , Kakamega',
    'Kakamega , Kakamega',
    'Vihiga',
    'Emuhaya , Vihiga',
    'Hamisi , Vihiga',
    'Sabatia , Vihiga',
    'Vihiga , Vihiga',
    'Bungoma',
    'Kanduyi , Bungoma',
    'Sirisia , Bungoma',
    'Webuye , Bungoma',
    'Bumula , Bungoma',
    'Kwilili , Bungoma',
    'Bungoma Town , Bungoma',
    'Mt.Elgon , Bungoma',
    'Kimilili , Bungoma',
    'Busia',
    'Nambale , Busia',
    'Nambale , Nambale , Busia',
    'Budalangi , Busia',
    'Budalangi , Budalangi , Busia',
    'Butula , Busia',
    'Butula , Butula , Busia',
    'Teso , Busia',
    'Teso , Teso , Busia',
    'Matayos , Busia',
    'Matayos , Matayos , Busia',
    'Funyula , Busia',
    'Funyula , Funyula , Busia',
    'Siaya',
    'Alego , Siaya',
    'Bondo , Siaya',
    'Gem , Siaya',
    'Rarieda , Siaya',
    'Ugenya , Siaya',
    'Kisumu',
    'Kisumu East , Kisumu',
    'Kisumu East , Kisumu East , Kisumu',
    'Kisumu West , Kisumu',
    'Market , Kisumu West , Kisumu',
    'Stadium , Kisumu West , Kisumu',
    'Aerodrome , Kisumu West , Kisumu',
    'Kibuye , Kisumu West , Kisumu',
    'Kisumu Central , Kisumu West , Kisumu',
    'Kisumu North , Kisumu West , Kisumu',
    'Milimoni , Kisumu West , Kisumu',
    'Railway , Kisumu West , Kisumu',
    'Southwest Kisumu , Kisumu West , Kisumu',
    'kisumu Central , Kisumu',
    'Kisumu Central Area , kisumu Central , Kisumu',
    'Riat Hills , kisumu Central , Kisumu',
    'Seme , Kisumu',
    'Seme , Seme , Kisumu',
    'Nyando , Kisumu',
    'Nyando , Nyando , Kisumu',
    'Muhoroni , Kisumu',
    'Muhoroni , Muhoroni , Kisumu',
    'Nyakach , Kisumu',
    'Nyakach , Nyakach , Kisumu',
    'Mamboleo , Kisumu',
    'Kisumu CBD , Kisumu',
    'Nyamasaria , Kisumu',
    'Konya , Kisumu',
    'Kajulu , Kisumu',
    'Buoye , Kisumu',
    'Kiboswa , Kisumu',
    'Homa Bay',
    'Ndhiwa , Homa Bay',
    'Ndhiwa , Ndhiwa , Homa Bay',
    'Rangwe , Homa Bay',
    'Rangwe , Rangwe , Homa Bay',
    'Migori',
    'Migori , Migori',
    'Migori , Migori , Migori',
    'Nyatike , Migori',
    'Nyatike , Nyatike , Migori',
    'Rongo , Migori',
    'Rongo , Rongo , Migori',
    'Uriri , Migori',
    'Uriri , Uriri , Migori',
    'Kisii',
    'Bonchari , Kisii',
    'Kituti Chache , Kisii',
    'Nyaribari Chache , Kisii',
    'Ruiru',
    'Kamakis , Ruiru',
    'Membley , Ruiru',
    'Ngong',
    'Thika',
    'Kabati , Thika',
    'Kikuyu',
    'Wangige , Kikuyu',
    'Thogoto , Kikuyu',
    'Mariakani',
    'Mariakani , Mariakani',
    'Limuru',
    'Tigoni , Limuru',
    'Kitengela',
    'Kisaju , Kitengela',
    'Kinoo',
    'Kiserian',
    'Kiserian , Kiserian',
    'Matasia , Kiserian',
    'Athi River',
    'Mua Hills , Athi River',
    'Lukenya , Athi River',
    'Nanyuki',
    'Nanyuki , Nanyuki',
    'Isinya',
    'Isinya , Isinya',
    'Watamu',
    'Watamu , Watamu',
    'Kangundo',
    'Kangundo Road , Kangundo',
    'Naivasha',
    'Malindi',
    'Juja',
    'Mangu , Juja',
    'Nyahururu',
    'Nyahururu , Nyahururu',
    'Namanga',
    'Namanga , Namanga',
    'Sagana',
    'Sagana , Sagana',
    'Muranga',
    'Muranga , Muranga',
    'Kenol , Muranga',
    'Mai Mahiu',
    'Gilgil',
    'Kitale',
    'Kitale Town , Kitale',
    'Kamulu',
    'Kamulu , Kamulu',
    'Msambweni',
    'Ukunda',
  ];
  
  const uganda = [
    'Central',
    'Buikwe , Central',
    'Bukomansimbi , Central',
    'Butambala , Central',
    'Buvuma , Central',
    'Gomba , Central',
    'Kalangala , Central',
    'Kalungu , Central',
    'Kampala , Central',
    'Kisaasi , Kampala , Central',
    'Nakawa , Kampala , Central',
    'Bukoto , Kampala , Central',
    'Munyonyo , Kampala , Central',
    'Gabba , Kampala , Central',
    'Kyambogo , Kampala , Central',
    'Kampala Central , Kampala , Central',
    'Kansanga , Kampala , Central',
    'Bugolobi , Kampala , Central',
    'Bulambiro , Kampala , Central',
    'Buye , Kampala , Central',
    'Bwaise , Kampala , Central',
    'Kigowa , Kampala , Central',
    'Kyebando , Kampala , Central',
    'Lugala , Kampala , Central',
    'Luzira , Kampala , Central',
    'Makerere , Kampala , Central',
    'Mbuya , Kampala , Central',
    'Mengo , Kampala , Central',
    'Mpanga , Kampala , Central',
    'Mulago , Kampala , Central',
    'Namirembe , Kampala , Central',
    'Port Bell , Kampala , Central',
    'Lubaga , Kampala , Central',
    'Makindye , Kampala , Central',
    'Kasanda , Central',
    'Kayunga , Central',
    'Kiboga , Central',
    'Kyankwanzi , Central',
    'Kyotera , Central',
    'Luweero , Central',
    'Lwengo , Central',
    'Lyantonde , Central',
    'Masaka , Central',
    'Mityana , Central',
    'Mpigi , Central',
    'Mubende , Central',
    'Mukono , Central',
    'Mukono , Mukono , Central',
    'Bajo , Mukono , Central',
    'Banda , Mukono , Central',
    'Banga , Mukono , Central',
    'Bugigi , Mukono , Central',
    'Buita , Mukono , Central',
    'Bujagali , Mukono , Central',
    'Bukerere , Mukono , Central',
    'Bukuku , Mukono , Central',
    'Buloba , Mukono , Central',
    'Bunakijja , Mukono , Central',
    'Bunyiri , Mukono , Central',
    'Buwaya , Mukono , Central',
    'Damba , Mukono , Central',
    'Gaba , Mukono , Central',
    'Gavu , Mukono , Central',
    'Gegede , Mukono , Central',
    'Gimbi , Mukono , Central',
    'Gobero , Mukono , Central',
    'Goma , Mukono , Central',
    'Gonve , Mukono , Central',
    'kabembe , Mukono , Central',
    'Kagulu , Mukono , Central',
    'Kakakala , Mukono , Central',
    'Kakinzi , Mukono , Central',
    'Kakira , Mukono , Central',
    'Kalagala , Mukono , Central',
    'Nakaseke , Central',
    'Nakasongola , Central',
    'Rakai , Central',
    'Sembabule , Central',
    'Wakiso , Central',
    'Kira , Wakiso , Central',
    'Gayaza , Wakiso , Central',
    'Kasanje , Wakiso , Central',
    'Nsangi , Wakiso , Central',
    'Nangaba , Wakiso , Central',
    'Namayumba , Wakiso , Central',
    'Nabweru , Wakiso , Central',
    'Masulita , Wakiso , Central',
    'Ssabagado-Makindye , Wakiso , Central',
    'Kawempe , Wakiso , Central',
    'Katabi , Wakiso , Central',
    'Eastern',
    'Amuria , Eastern',
    'Budaka , Eastern',
    'Bududa , Eastern',
    'Bugiri , Eastern',
    'Bugweri , Eastern',
    'Bukedea , Eastern',
    'Bukwo , Eastern',
    'Bulambuli , Eastern',
    'Busia , Eastern',
    'Butaleja , Eastern',
    'Butebo , Eastern',
    'Buyende , Eastern',
    'Iganga , Eastern',
    'Jinja , Eastern',
    'Bugembe , Jinja , Eastern',
    'Buwenge , Jinja , Eastern',
    'Kaberamaido , Eastern',
    'Kaliro , Eastern',
    'Kamuli , Eastern',
    'Kapchorwa , Eastern',
    'Katakwi , Eastern',
    'Kibuku , Eastern',
    'Kumi , Eastern',
    'Kween , Eastern',
    'Luuka , Eastern',
    'Manafwa , Eastern',
    'Mayuge , Eastern',
    'Mbale , Eastern',
    'Namayingo , Eastern',
    'Namisindwa , Eastern',
    'Namutumba , Eastern',
    'Ngora , Eastern',
    'Pallisa , Eastern',
    'Serere , Eastern',
    'Sironko , Eastern',
    'Soroti , Eastern',
    'Tororo , Eastern',
    'Northern',
    'Abim , Northern',
    'Adjumani , Northern',
    'Agago , Northern',
    'Alebtong , Northern',
    'Amolatar , Northern',
    'Amudat , Northern',
    'Amuru , Northern',
    'Apac , Northern',
    'Arua , Northern',
    'Dokolo , Northern',
    'Gulu , Northern',
    'Kaabong , Northern',
    'Kapelebyong , Northern',
    'Kitgum , Northern',
    'Koboko , Northern',
    'Kole , Northern',
    'Kotido , Northern',
    'Kwania , Northern',
    'Lamwo , Northern',
    'Lira , Northern',
    'Maracha , Northern',
    'Moroto , Northern',
    'Moyo , Northern',
    'Nabilatuk , Northern',
    'Nakapiripirit , Northern',
    'Napak , Northern',
    'Nebbi , Northern',
    'Nwoya , Northern',
    'Omoro , Northern',
    'Otuke , Northern',
    'Oyam , Northern',
    'Pader , Northern',
    'Pakwach , Northern',
    'Yumbe , Northern',
    'Zombo , Northern',
    'Western',
    'Buhweju , Western',
    'Buliisa , Western',
    'Bundibugyo , Western',
    'Bunyangabu , Western',
    'Bushenyi , Western',
    'Hoima , Western',
    'Ibanda , Western',
    'Isingiro , Western',
    'Kabale , Western',
    'Kabarole , Western',
    'Kagadi , Western',
    'Kakumiro , Western',
    'Kamwenge , Western',
    'Kanungu , Western',
    'Kasese , Western',
    'Kibaale , Western',
    'Kiruhura , Western',
    'Kiryandongo , Western',
    'Kisoro , Western',
    'Kyegegwa , Western',
    'Kyenjojo , Western',
    'Masindi , Western',
    'Mbarara , Western',
    'Mitooma , Western',
    'Ntoroko , Western',
    'Ntungamo , Western',
    'Rubanda , Western',
    'Rubirizi , Western',
    'Rukiga , Western',
    'Rukungiri , Western',
    'Sheema , Western',
  ];
  
  const countries: {[key: string]: any} = { nigeria, kenya, uganda };
  
  const useGoodTenantsCountryLibrary = () => {
  
    function getStates(country: any) {
      const data = countries[country];
  
      const states = new Set();
      data?.forEach((location: any) => {
        const parts = location.split(',').map((part: any) => part.trim());
        if (parts.length === 3) {
          states.add(parts[2]); // subarea, area, state
        } else if (parts.length === 2) {
          states.add(parts[1]); // area, state
        } else if (parts.length === 1) {
          states.add(parts[0]); // state
        }
      });
      return Array.from(states).sort();
    }
  
    function getAreasByState(state: any, country: any) {
      const data = countries[country];
      const areas = new Set();
      data?.forEach((location: any) => {
        const parts = location.split(',').map((part: any) => part.trim());
        if (parts.length === 3 && parts[2] === state) {
          areas.add(parts[1]); // subarea, area, state
        } else if (parts.length === 2 && parts[1] === state) {
          areas.add(parts[0]); // area, state
        }
      });
      return Array.from(areas).sort();
    }
  
    function getSubareasByArea(area: any, state: any, country: any) {
      const data = countries[country];
  
      const subareas = new Set();
      data?.forEach((location: any) => {
        const parts = location.split(',').map((part: any) => part.trim());
        if (
          parts.length === 3 &&
          parts[1] === area &&
          (state === null || parts[2] === state)
        ) {
          subareas.add(parts[0]); // subarea, area, state
        }
      });
      return Array.from(subareas).sort();
    }
  
    return { getStates, getAreasByState, getSubareasByArea };
  }
  
export default useGoodTenantsCountryLibrary;